import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';

const APP_DIR = join(__dirname, '..', 'examples', 'expo-react');

const read = (file: string) => readFileSync(join(APP_DIR, file), 'utf8');

type IScreenSpec = {
  route: string;
  pkg: string;
  // Соседние файлы экрана, если он разбит по размеру
  parts?: readonly string[];
  // Публичные экспорты и поля опций пакета, каждое должно быть на экране
  surface: readonly string[];
};

const SCREENS: readonly IScreenSpec[] = [
  {
    route: 'MailComposer',
    pkg: '@symbiote-native/mail-composer',
    surface: [
      'composeAsync',
      'isAvailableAsync',
      'getClients',
      'recipients',
      'ccRecipients',
      'bccRecipients',
      'subject',
      'body',
      'isHtml',
      'attachments',
    ],
  },
  {
    route: 'Print',
    pkg: '@symbiote-native/print',
    surface: [
      'printAsync',
      'selectPrinterAsync',
      'printToFileAsync',
      'Orientation',
      'uri',
      'html',
      'width',
      'height',
      'printerUrl',
      'orientation',
      'margins',
      'base64',
      'textZoom',
    ],
  },
  {
    route: 'Speech',
    pkg: '@symbiote-native/speech',
    surface: [
      'speak',
      'getAvailableVoicesAsync',
      'isSpeakingAsync',
      'stop',
      'pause',
      'resume',
      'maxSpeechInputLength',
      'VoiceQuality',
      'language',
      'pitch',
      'rate',
      'volume',
      'voice',
      'useApplicationAudioSession',
      'onStart',
      'onStopped',
      'onDone',
      'onError',
      'onBoundary',
    ],
  },
  {
    route: 'VideoThumbnails',
    pkg: '@symbiote-native/video-thumbnails',
    surface: ['getThumbnailAsync', 'time', 'quality', 'headers'],
  },
  {
    route: 'DocumentPicker',
    pkg: '@symbiote-native/document-picker',
    surface: [
      'getDocumentAsync',
      'type',
      'copyToCacheDirectory',
      'multiple',
      'canceled',
      'assets',
      'name',
      'size',
      'uri',
      'mimeType',
      'lastModified',
    ],
  },
  {
    route: 'ImagePicker',
    pkg: '@symbiote-native/image-picker',
    parts: ['screens/image-picker-options.tsx'],
    surface: [
      'launchImageLibraryAsync',
      'launchCameraAsync',
      'getPendingResultAsync',
      'getCameraPermissionsAsync',
      'requestCameraPermissionsAsync',
      'getMediaLibraryPermissionsAsync',
      'requestMediaLibraryPermissionsAsync',
      'useCameraPermissions',
      'useMediaLibraryPermissions',
      'allowsEditing',
      'aspect',
      'shape',
      'quality',
      'mediaTypes',
      'exif',
      'base64',
      'videoExportPreset',
      'videoQuality',
      'allowsMultipleSelection',
      'selectionLimit',
      'orderedSelection',
      'defaultTab',
      'videoMaxDuration',
      'presentationStyle',
      'cameraType',
      'preferredAssetRepresentationMode',
      'shouldDownloadFromNetwork',
      'VideoExportPreset',
      'UIImagePickerControllerQualityType',
      'UIImagePickerPresentationStyle',
      'UIImagePickerPreferredAssetRepresentationMode',
      'CameraType',
      'granted',
      'canAskAgain',
      'accessPrivileges',
      'fileName',
      'fileSize',
      'duration',
      'assetId',
      'pairedVideoAsset',
    ],
  },
  {
    route: 'ImageManipulator',
    pkg: '@symbiote-native/image-manipulator',
    surface: [
      'manipulate',
      'manipulateAsync',
      'useImageManipulator',
      'FlipType',
      'SaveFormat',
      'resize',
      'rotate',
      'flip',
      'crop',
      'reset',
      'renderAsync',
      'saveAsync',
      'compress',
      'base64',
      'format',
    ],
  },
  {
    route: 'Sqlite',
    pkg: '@symbiote-native/sqlite',
    parts: [
      'screens/sqlite-database.tsx',
      'screens/sqlite-standalone.tsx',
      'screens/sqlite-kv.tsx',
    ],
    surface: [
      'SQLiteProvider',
      'useSQLiteContext',
      'useSuspense',
      'onInit',
      'onError',
      'enableChangeListener',
      'useNewConnection',
      'finalizeUnusedStatementsBeforeClosing',
      'libSQLOptions',
      'isInTransactionAsync',
      'closeAsync',
      'execAsync',
      'serializeAsync',
      'prepareAsync',
      'createSessionAsync',
      'loadExtensionAsync',
      'withTransactionAsync',
      'withExclusiveTransactionAsync',
      'runAsync',
      'getFirstAsync',
      'getEachAsync',
      'getAllAsync',
      'isInTransactionSync',
      'closeSync',
      'execSync',
      'serializeSync',
      'prepareSync',
      'createSessionSync',
      'loadExtensionSync',
      'withTransactionSync',
      'runSync',
      'getFirstSync',
      'getEachSync',
      'getAllSync',
      'syncLibSQL',
      'sql',
      'values',
      'first',
      'each',
      'allSync',
      'valuesSync',
      'firstSync',
      'eachSync',
      'executeAsync',
      'executeForRawResultAsync',
      'getColumnNamesAsync',
      'finalizeAsync',
      'executeSync',
      'getColumnNamesSync',
      'finalizeSync',
      'resetAsync',
      'resetSync',
      'lastInsertRowId',
      'changes',
      'attachAsync',
      'enableAsync',
      'createChangesetAsync',
      'createInvertedChangesetAsync',
      'applyChangesetAsync',
      'invertChangesetAsync',
      'attachSync',
      'enableSync',
      'createChangesetSync',
      'createInvertedChangesetSync',
      'applyChangesetSync',
      'invertChangesetSync',
      'defaultDatabaseDirectory',
      'bundledExtensions',
      'openDatabaseAsync',
      'openDatabaseSync',
      'deserializeDatabaseAsync',
      'deserializeDatabaseSync',
      'deleteDatabaseAsync',
      'deleteDatabaseSync',
      'backupDatabaseAsync',
      'backupDatabaseSync',
      'addDatabaseChangeListener',
      'importDatabaseFromAssetAsync',
      'parseSQLQuery',
      'createDatabasePath',
      'basename',
      'AsyncStorage',
      'Storage',
      'SQLiteStorage',
      'getItemAsync',
      'setItemAsync',
      'removeItemAsync',
      'getAllKeysAsync',
      'clearAsync',
      'getLengthAsync',
      'getKeyByIndexAsync',
      'getItemSync',
      'setItemSync',
      'removeItemSync',
      'getAllKeysSync',
      'clearSync',
      'getLengthSync',
      'getKeyByIndexSync',
      'getItem',
      'setItem',
      'removeItem',
      'getAllKeys',
      'clear',
      'mergeItem',
      'multiGet',
      'multiSet',
      'multiRemove',
      'multiMerge',
    ],
  },
  {
    route: 'FileSystem',
    pkg: '@symbiote-native/file-system',
    parts: [
      'screens/file-system-modern.tsx',
      'screens/file-system-network.tsx',
      'screens/file-system-legacy.tsx',
    ],
    surface: [
      'File',
      'Directory',
      'Paths',
      'UploadTask',
      'DownloadTask',
      'appleSharedContainers',
      'totalDiskSpace',
      'availableDiskSpace',
      'pickDirectoryAsync',
      'pickFileAsync',
      'downloadFileAsync',
      'createDownloadTask',
      'createUploadTask',
      'upload',
      'watch',
      'text',
      'textSync',
      'base64',
      'base64Sync',
      'bytes',
      'bytesSync',
      'write',
      'create',
      'copy',
      'copySync',
      'move',
      'moveSync',
      'rename',
      'open',
      'md5',
      'modificationTime',
      'creationTime',
      'contentUri',
      'extension',
      'parentDirectory',
      'readableStream',
      'writableStream',
      'arrayBuffer',
      'json',
      'formData',
      'stream',
      'slice',
      'readBytes',
      'writeBytes',
      'createFile',
      'createDirectory',
      'list',
      'listAsRecords',
      'info',
      'intermediates',
      'overwrite',
      'idempotent',
      'encoding',
      'append',
      'mimeTypes',
      'multipleFiles',
      'initialUri',
      'debounce',
      'events',
      'headers',
      'onProgress',
      'signal',
      'FileMode',
      'FileSystemEncodingType',
      'FileSystemUploadType',
      'httpMethod',
      'uploadType',
      'fieldName',
      'parameters',
      'sessionType',
      'downloadAsync',
      'pause',
      'pauseAsync',
      'resumeAsync',
      'cancel',
      'release',
      'savable',
      'fromSavable',
      'uploadAsync',
      'documentDirectory',
      'cacheDirectory',
      'bundleDirectory',
      'getInfoAsync',
      'readAsStringAsync',
      'getContentUriAsync',
      'writeAsStringAsync',
      'deleteAsync',
      'moveAsync',
      'copyAsync',
      'makeDirectoryAsync',
      'readDirectoryAsync',
      'getFreeDiskStorageAsync',
      'getTotalDiskCapacityAsync',
      'createDownloadResumable',
      'StorageAccessFramework',
      'getUriForDirectoryInRoot',
      'requestDirectoryPermissionsAsync',
      'position',
      'length',
    ],
  },
  {
    route: 'MediaLibrary',
    pkg: '@symbiote-native/media-library',
    parts: [
      'screens/media-library-modern.tsx',
      'screens/media-library-legacy.tsx',
    ],
    surface: [
      'Query',
      'gt',
      'gte',
      'lt',
      'lte',
      'limit',
      'offset',
      'orderBy',
      'exe',
      'exeForMetadata',
      'Asset',
      'getCreationTime',
      'getDuration',
      'getFilename',
      'getHeight',
      'getMediaType',
      'getMediaSubtypes',
      'getLivePhotoVideoUri',
      'getIsInCloud',
      'getOrientation',
      'getModificationTime',
      'getShape',
      'getUri',
      'getWidth',
      'getInfo',
      'getAlbums',
      'getLocation',
      'getExif',
      'getFavorite',
      'setFavorite',
      'Album',
      'getAssets',
      'getTitle',
      'add',
      'removeAssets',
      'getAll',
      'requestPermissionsAsync',
      'getPermissionsAsync',
      'usePermissions',
      'presentPermissionsPicker',
      'presentPermissionsPickerAsync',
      'addListener',
      'removeAllListeners',
      'AssetField',
      'MediaType',
      'MediaSubtype',
      'writeOnly',
      'granularPermissions',
      'isAvailableAsync',
      'createAssetAsync',
      'saveToLibraryAsync',
      'addAssetsToAlbumAsync',
      'removeAssetsFromAlbumAsync',
      'deleteAssetsAsync',
      'getAssetInfoAsync',
      'getAssetContentUriAsync',
      'getAlbumsAsync',
      'getAlbumAsync',
      'createAlbumAsync',
      'deleteAlbumsAsync',
      'getAssetsAsync',
      'getMomentsAsync',
      'migrateAlbumIfNeededAsync',
      'albumNeedsMigrationAsync',
      'setAssetFavoriteAsync',
      'SortBy',
      'first',
      'after',
      'sortBy',
      'mediaSubtypes',
      'createdAfter',
      'createdBefore',
      'resolveWithFullInfo',
      'includeSmartAlbums',
      'shouldDownloadFromNetwork',
    ],
  },
  {
    route: 'Location',
    pkg: '@symbiote-native/location',
    parts: ['screens/location-cards.tsx', 'screens/location-background.tsx'],
    surface: [
      'getProviderStatusAsync',
      'enableNetworkProviderAsync',
      'getCurrentPositionAsync',
      'getLastKnownPositionAsync',
      'watchPositionAsync',
      'watchHeadingAsync',
      'getHeadingAsync',
      'geocodeAsync',
      'reverseGeocodeAsync',
      'getForegroundPermissionsAsync',
      'requestForegroundPermissionsAsync',
      'getBackgroundPermissionsAsync',
      'requestBackgroundPermissionsAsync',
      'hasServicesEnabledAsync',
      'getMotionActivityPermissionsAsync',
      'requestMotionActivityPermissionsAsync',
      'getMotionActivityAsync',
      'watchMotionActivityAsync',
      'isBackgroundLocationAvailableAsync',
      'startLocationUpdatesAsync',
      'stopLocationUpdatesAsync',
      'hasStartedLocationUpdatesAsync',
      'startGeofencingAsync',
      'stopGeofencingAsync',
      'hasStartedGeofencingAsync',
      'useForegroundPermissions',
      'useBackgroundPermissions',
      'useMotionActivityPermissions',
      'installWebGeolocationPolyfill',
      'getCurrentWatchId',
      'Accuracy',
      'ActivityType',
      'GeofencingEventType',
      'GeofencingRegionState',
      'MotionActivityConfidence',
      'mayShowUserSettingsDialog',
      'timeInterval',
      'distanceInterval',
      'maxAge',
      'requiredAccuracy',
      'showsBackgroundLocationIndicator',
      'deferredUpdatesDistance',
      'deferredUpdatesTimeout',
      'deferredUpdatesInterval',
      'activityType',
      'pausesUpdatesAutomatically',
      'foregroundService',
      'notificationTitle',
      'notificationBody',
      'notificationColor',
      'killServiceOnDestroy',
      'identifier',
      'radius',
      'notifyOnEnter',
      'notifyOnExit',
    ],
  },
  {
    route: 'SecureStore',
    pkg: '@symbiote-native/secure-store',
    parts: ['screens/secure-store-extras.tsx'],
    surface: [
      'isAvailableAsync',
      'getItemAsync',
      'getItem',
      'setItemAsync',
      'setItem',
      'deleteItemAsync',
      'canUseBiometricAuthentication',
      'keychainService',
      'requireAuthentication',
      'authenticationPrompt',
      'keychainAccessible',
      'accessGroup',
      'AFTER_FIRST_UNLOCK',
      'AFTER_FIRST_UNLOCK_THIS_DEVICE_ONLY',
      'ALWAYS',
      'ALWAYS_THIS_DEVICE_ONLY',
      'WHEN_PASSCODE_SET_THIS_DEVICE_ONLY',
      'WHEN_UNLOCKED',
      'WHEN_UNLOCKED_THIS_DEVICE_ONLY',
    ],
  },
  {
    route: 'Sharing',
    pkg: '@symbiote-native/sharing',
    parts: ['screens/sharing-extras.tsx'],
    surface: [
      'isAvailableAsync',
      'shareAsync',
      'mimeType',
      'UTI',
      'dialogTitle',
      'anchor',
      'getSharedPayloads',
      'getResolvedSharedPayloadsAsync',
      'clearSharedPayloads',
      'useIncomingShare',
      'sharedPayloads',
      'resolvedSharedPayloads',
      'isResolving',
      'refreshSharePayloads',
      'contentUri',
      'contentType',
      'contentMimeType',
      'originalName',
      'contentSize',
      'shareType',
    ],
  },
  {
    route: 'WebBrowser',
    pkg: '@symbiote-native/web-browser',
    parts: ['screens/web-browser-extras.tsx'],
    surface: [
      'openBrowserAsync',
      'dismissBrowser',
      'openAuthSessionAsync',
      'dismissAuthSession',
      'maybeCompleteAuthSession',
      'warmUpAsync',
      'coolDownAsync',
      'mayInitWithUrlAsync',
      'getCustomTabsSupportingBrowsersAsync',
      'WebBrowserResultType',
      'WebBrowserPresentationStyle',
      'toolbarColor',
      'browserPackage',
      'enableBarCollapsing',
      'secondaryToolbarColor',
      'showTitle',
      'enableDefaultShareMenuItem',
      'showInRecents',
      'createTask',
      'useProxyActivity',
      'controlsColor',
      'dismissButtonStyle',
      'readerMode',
      'presentationStyle',
      'preferEphemeralSession',
      'preferUniversalLinks',
      'skipRedirectCheck',
    ],
  },
  {
    route: 'BackgroundTasks',
    pkg: '@symbiote-native/task-manager',
    parts: ['screens/background-tasks-extras.tsx'],
    surface: [
      'defineTask',
      'isTaskDefined',
      'isTaskRegisteredAsync',
      'getTaskOptionsAsync',
      'getRegisteredTasksAsync',
      'unregisterTaskAsync',
      'unregisterAllTasksAsync',
      'isAvailableAsync',
      'getStatusAsync',
      'setMinimumIntervalAsync',
      'registerTaskAsync',
      'triggerTaskWorkerForTestingAsync',
      'addExpirationListener',
      'BackgroundFetchResult',
      'BackgroundFetchStatus',
      'BackgroundTaskResult',
      'BackgroundTaskStatus',
      'minimumInterval',
      'stopOnTerminate',
      'startOnBoot',
    ],
  },
  {
    route: 'AuthSession',
    pkg: '@symbiote-native/auth-session',
    parts: [
      'screens/auth-session-request.tsx',
      'screens/auth-session-tokens.tsx',
      'screens/auth-session-providers.tsx',
    ],
    surface: [
      'AuthRequest',
      'ResponseType',
      'CodeChallengeMethod',
      'Prompt',
      'dismiss',
      'loadAsync',
      'makeRedirectUri',
      'fetchDiscoveryAsync',
      'issuerWithWellKnownUrl',
      'resolveDiscoveryAsync',
      'requestAsync',
      'AccessTokenRequest',
      'RefreshTokenRequest',
      'RevokeTokenRequest',
      'TokenResponse',
      'exchangeCodeAsync',
      'fetchUserInfoAsync',
      'getCurrentTimeInSeconds',
      'refreshAsync',
      'revokeAsync',
      'GrantType',
      'TokenTypeHint',
      'AuthError',
      'ResponseError',
      'TokenError',
      'useAuthRequest',
      'useAuthRequestResult',
      'useAutoDiscovery',
      'useLoadedAuthRequest',
      'useGoogleAuthRequest',
      'useGoogleIdTokenAuthRequest',
      'useFacebookAuthRequest',
      'GoogleAuthRequest',
      'FacebookAuthRequest',
      'googleDiscovery',
      'facebookDiscovery',
      'clientId',
      'redirectUri',
      'scopes',
      'clientSecret',
      'codeChallengeMethod',
      'state',
      'extraParams',
      'usePKCE',
      'scheme',
      'queryParams',
      'isTripleSlashed',
      'preferLocalhost',
      'native',
      'promptAsync',
      'makeAuthUrlAsync',
      'parseReturnUrl',
      'getAuthRequestConfigAsync',
      'isTokenFresh',
      'shouldRefresh',
      'fromQueryParams',
      'getRequestConfig',
      'loginHint',
      'selectAccount',
      'webClientId',
      'iosClientId',
      'androidClientId',
      'shouldAutoExchangeCode',
    ],
  },
  {
    route: 'Font',
    pkg: '@symbiote-native/font',
    surface: [
      'loadAsync',
      'unloadAsync',
      'unloadAllAsync',
      'isLoaded',
      'isLoading',
      'getLoadedFonts',
      'renderToImageAsync',
      'useFonts',
      'FontDisplay',
      'display',
      'testString',
      'uri',
      'fontFamily',
      'size',
      'color',
      'lineHeight',
      'Asset',
    ],
  },
  {
    route: 'Asset',
    pkg: '@symbiote-native/asset',
    surface: [
      'Asset',
      'loadAsync',
      'fromModule',
      'fromMetadata',
      'fromURI',
      'downloadAsync',
      'useAssets',
      'name',
      'type',
      'hash',
      'uri',
      'localUri',
      'width',
      'height',
      'downloaded',
      'ANDROID_EMBEDDED_URL_BASE_RESOURCE',
    ],
  },
  {
    route: 'AppMetrics',
    pkg: '@symbiote-native/app-metrics',
    parts: ['screens/app-metrics-sessions.tsx'],
    surface: [
      'markFirstRender',
      'markInteractive',
      'logEvent',
      'setGlobalAttributes',
      'clearStoredEntries',
      'getInactiveSessions',
      'getAllCrashReports',
      'reportError',
      'getMainSession',
      'getForegroundSession',
      'Session',
      'NetworkRequestObserver',
      'AppMetricsRoot',
      'AppMetricsErrorBoundary',
      'useNetworkRequestObserver',
      'resetError',
      'isActive',
      'getEndDate',
      'getMetrics',
      'getLogs',
      'addMetric',
      'setFilter',
      'hosts',
      'methods',
      'onStarted',
      'onCompleted',
      'routeName',
      'displayName',
      'severity',
      'attributes',
      'source',
      'isFatal',
      'componentStack',
      'stacktrace',
      'fallback',
    ],
  },
  {
    route: 'AgeRange',
    pkg: '@symbiote-native/age-range',
    surface: [
      'requestAgeRangeAsync',
      'isEligibleForAgeFeaturesAsync',
      'showSignificantUpdateAcknowledgmentAsync',
      'getRequiredRegulatoryFeaturesAsync',
      'requestAgeSignalsAccessAsync',
      'setFakeAgeSignals',
      'threshold1',
      'threshold2',
      'threshold3',
      'lowerBound',
      'upperBound',
      'ageRangeDeclaration',
      'activeParentalControls',
      'installId',
      'ageRangeSource',
      'significantChangeStatus',
      'significantChangeApprovalDate',
      'mostRecentApprovalDate',
      'ageSignalsStatus',
      'errorCode',
    ],
  },
  {
    route: 'AppIntegrity',
    pkg: '@symbiote-native/app-integrity',
    surface: [
      'isSupported',
      'generateKeyAsync',
      'attestKeyAsync',
      'generateAssertionAsync',
      'prepareIntegrityTokenProviderAsync',
      'requestIntegrityCheckAsync',
      'isHardwareAttestationSupportedAsync',
      'generateHardwareAttestedKeyAsync',
      'getAttestationCertificateChainAsync',
      'keyId',
      'challenge',
      'cloudProjectNumber',
      'requestHash',
      'keyAlias',
    ],
  },
  {
    route: 'IntentLauncher',
    pkg: '@symbiote-native/intent-launcher',
    surface: [
      'startActivityAsync',
      'openApplication',
      'getApplicationIconAsync',
      'ActivityAction',
      'ResultCode',
      'resultCode',
      'type',
      'category',
      'extra',
      'data',
      'flags',
      'packageName',
      'className',
    ],
  },
  {
    route: 'NavigationBar',
    pkg: '@symbiote-native/navigation-bar',
    surface: [
      'setStyle',
      'setHidden',
      'addVisibilityListener',
      'setVisibilityAsync',
      'getVisibilityAsync',
      'pushStackEntry',
      'popStackEntry',
      'replaceStackEntry',
      'NavigationBar',
      'useVisibility',
      'rawVisibility',
    ],
  },
  {
    route: 'Calendar',
    pkg: '@symbiote-native/calendar',
    parts: [
      'screens/calendar-form.tsx',
      'screens/calendar-modern.tsx',
      'screens/calendar-legacy.tsx',
    ],
    surface: [
      'getCalendars',
      'getDefaultCalendarSync',
      'getSourcesSync',
      'createCalendar',
      'presentPicker',
      'listEvents',
      'listReminders',
      'createEvent',
      'createReminder',
      'addEventWithForm',
      'getOccurrenceSync',
      'getAttendees',
      'createAttendee',
      'openInCalendar',
      'editInCalendar',
      'ExpoCalendar',
      'ExpoCalendarEvent',
      'ExpoCalendarAttendee',
      'ExpoCalendarReminder',
      'getCalendarPermissions',
      'requestCalendarPermissions',
      'getRemindersPermissions',
      'requestRemindersPermissions',
      'useCalendarPermissions',
      'useRemindersPermissions',
      'writeOnly',
      'recurrenceRule',
      'frequency',
      'interval',
      'daysOfTheWeek',
      'alarms',
      'relativeOffset',
      'method',
      'availability',
      'status',
      'accessLevel',
      'allDay',
      'guestsCanModify',
      'guestsCanInviteOthers',
      'guestsCanSeeGuests',
      'EntityTypes',
      'ReminderStatus',
      'createEventInCalendarAsync',
      'openEventInCalendarAsync',
      'editEventInCalendarAsync',
      'isAvailableAsync',
      'getCalendarsAsync',
      'createCalendarAsync',
      'updateCalendarAsync',
      'deleteCalendarAsync',
      'getEventsAsync',
      'getEventAsync',
      'createEventAsync',
      'updateEventAsync',
      'deleteEventAsync',
      'getAttendeesForEventAsync',
      'createAttendeeAsync',
      'updateAttendeeAsync',
      'deleteAttendeeAsync',
      'getDefaultCalendarAsync',
      'getSourcesAsync',
      'getSourceAsync',
      'openEventInCalendar',
      'getRemindersAsync',
      'getReminderAsync',
      'createReminderAsync',
      'updateReminderAsync',
      'deleteReminderAsync',
      'getCalendarPermissionsAsync',
      'getRemindersPermissionsAsync',
      'requestCalendarPermissionsAsync',
      'requestPermissionsAsync',
      'requestRemindersPermissionsAsync',
    ],
  },
  {
    route: 'Contacts',
    pkg: '@symbiote-native/contacts',
    parts: [
      'screens/contacts-modern.tsx',
      'screens/contacts-instance.tsx',
      'screens/contacts-groups.tsx',
      'screens/contacts-legacy.tsx',
    ],
    surface: [
      'getAll',
      'getAllDetails',
      'getCount',
      'hasAny',
      'create',
      'presentCreateForm',
      'presentPicker',
      'presentAccessPicker',
      'patch',
      'update',
      'delete',
      'editWithForm',
      'getFullName',
      'getThumbnail',
      'getIsFavourite',
      'setIsFavourite',
      'getBirthday',
      'setBirthday',
      'getNonGregorianBirthday',
      'setNonGregorianBirthday',
      'getGivenName',
      'setGivenName',
      'getNote',
      'setImage',
      'addEmail',
      'getEmails',
      'deleteEmail',
      'updateEmail',
      'addPhone',
      'getPhones',
      'deletePhone',
      'updatePhone',
      'addDate',
      'getDates',
      'deleteDate',
      'updateDate',
      'addExtraName',
      'getExtraNames',
      'deleteExtraName',
      'updateExtraName',
      'addAddress',
      'getAddresses',
      'deleteAddress',
      'updateAddress',
      'addRelation',
      'getRelations',
      'deleteRelation',
      'updateRelation',
      'addUrlAddress',
      'getUrlAddresses',
      'deleteUrlAddress',
      'updateUrlAddress',
      'addSocialProfile',
      'getSocialProfiles',
      'deleteSocialProfile',
      'updateSocialProfile',
      'addImAddress',
      'getImAddresses',
      'deleteImAddress',
      'updateImAddress',
      'Group',
      'Container',
      'getName',
      'setName',
      'addContact',
      'removeContact',
      'getContacts',
      'getType',
      'getGroups',
      'getDefault',
      'getPermissionsAsync',
      'requestPermissionsAsync',
      'addContactsChangeListener',
      'removeAllContactsChangeListeners',
      'ContactAccessButton',
      'isAvailable',
      'caption',
      'ignoredEmails',
      'ignoredPhoneNumbers',
      'tintColor',
      'backgroundColor',
      'textColor',
      'limit',
      'offset',
      'sortOrder',
      'rawContacts',
      'isAvailableAsync',
      'hasContactsAsync',
      'getContactsAsync',
      'getPagedContactsAsync',
      'getContactByIdAsync',
      'addContactAsync',
      'updateContactAsync',
      'removeContactAsync',
      'presentFormAsync',
      'presentContactPickerAsync',
      'presentAccessPickerAsync',
      'writeContactToFileAsync',
      'shareContactAsync',
      'getDefaultContainerIdAsync',
      'getContainersAsync',
      'createGroupAsync',
      'getGroupsAsync',
      'updateGroupNameAsync',
      'removeGroupAsync',
      'addExistingContactToGroupAsync',
      'removeContactFromGroupAsync',
      'addExistingGroupToContainerAsync',
    ],
  },
  {
    route: 'ScreenCapture',
    pkg: '@symbiote-native/screen-capture',
    surface: [
      'preventScreenCaptureAsync',
      'allowScreenCaptureAsync',
      'enableAppSwitcherProtectionAsync',
      'disableAppSwitcherProtectionAsync',
      'addScreenshotListener',
      'removeScreenshotListener',
      'isAvailableAsync',
      'getPermissionsAsync',
      'requestPermissionsAsync',
      'usePreventScreenCapture',
      'useScreenshotListener',
      'usePermissions',
      'blurIntensity',
      'key',
    ],
  },
  {
    route: 'Blob',
    pkg: '@symbiote-native/blob',
    surface: [
      'Blob',
      'slice',
      'bytes',
      'text',
      'arrayBuffer',
      'stream',
      'size',
      'type',
      'endings',
    ],
  },
  {
    route: 'Audio',
    pkg: '@symbiote-native/audio',
    parts: [
      'screens/audio-player.tsx',
      'screens/audio-recorder.tsx',
      'screens/audio-playlist.tsx',
      'screens/audio-module-stream.tsx',
    ],
    surface: [
      'useAudioPlayer',
      'useAudioPlayerStatus',
      'useAudioSampleListener',
      'useAudioPlaylist',
      'useAudioPlaylistStatus',
      'useAudioRecorder',
      'useAudioRecorderState',
      'useAudioStream',
      'createAudioPlayer',
      'createAudioRecorder',
      'createAudioPlaylist',
      'createAudioStream',
      'AudioQuality',
      'IOSOutputFormat',
      'RecordingPresets',
      'setIsAudioActiveAsync',
      'setAudioModeAsync',
      'requestRecordingPermissionsAsync',
      'requestNotificationPermissionsAsync',
      'getRecordingPermissionsAsync',
      'preload',
      'clearPreloadedSource',
      'clearAllPreloadedSources',
      'getPreloadedSources',
      'PLAYBACK_STATUS_UPDATE',
      'AUDIO_SAMPLE_UPDATE',
      'RECORDING_STATUS_UPDATE',
      'PLAYLIST_STATUS_UPDATE',
      'TRACK_CHANGED',
      'AUDIO_STREAM_BUFFER',
      'AUDIO_STREAM_STATUS',
      'play',
      'pause',
      'replace',
      'seekTo',
      'setPlaybackRate',
      'setAudioSamplingEnabled',
      'setActiveForLockScreen',
      'updateLockScreenMetadata',
      'clearLockScreenControls',
      'remove',
      'updateInterval',
      'downloadFirst',
      'keepAudioSessionActive',
      'preferredForwardBufferDuration',
      'record',
      'stop',
      'prepareToRecordAsync',
      'getAvailableInputs',
      'getCurrentInput',
      'setInput',
      'getStatus',
      'startRecordingAtTime',
      'recordForDuration',
      'forDuration',
      'atTime',
      'isMeteringEnabled',
      'next',
      'previous',
      'skipTo',
      'add',
      'insert',
      'clear',
      'destroy',
      'start',
      'sampleRate',
      'channels',
      'encoding',
      'onBuffer',
      'playsInSilentMode',
      'interruptionMode',
      'allowsRecording',
      'shouldPlayInBackground',
      'shouldRouteThroughEarpiece',
      'allowsBackgroundRecording',
      'pitchCorrectionQuality',
    ],
  },
  {
    route: 'Sms',
    pkg: '@symbiote-native/sms',
    surface: [
      'isAvailableAsync',
      'sendSMSAsync',
      'attachments',
      'uri',
      'mimeType',
      'filename',
    ],
  },
  {
    route: 'Notifications',
    pkg: '@symbiote-native/notifications',
    parts: [
      'screens/notifications-setup.tsx',
      'screens/notifications-tokens.tsx',
      'screens/notifications-schedule.tsx',
      'screens/notifications-channels.tsx',
      'screens/notifications-events.tsx',
    ],
    surface: [
      'getPermissionsAsync',
      'requestPermissionsAsync',
      'allowAlert',
      'allowBadge',
      'allowSound',
      'allowDisplayInCarPlay',
      'allowCriticalAlerts',
      'provideAppNotificationSettings',
      'allowProvisional',
      'setNotificationHandler',
      'handleNotification',
      'handleSuccess',
      'handleError',
      'shouldShowBanner',
      'shouldShowList',
      'shouldPlaySound',
      'shouldSetBadge',
      'NotificationTimeoutError',
      'getBadgeCountAsync',
      'setBadgeCountAsync',
      'getDevicePushTokenAsync',
      'getExpoPushTokenAsync',
      'addPushTokenListener',
      'subscribeToTopicAsync',
      'unsubscribeFromTopicAsync',
      'unregisterForNotificationsAsync',
      'setAutoServerRegistrationEnabledAsync',
      'installPushTokenAutoRegistration',
      'projectId',
      'registerTaskAsync',
      'unregisterTaskAsync',
      'BackgroundNotificationTaskResult',
      'scheduleNotificationAsync',
      'cancelScheduledNotificationAsync',
      'cancelAllScheduledNotificationsAsync',
      'getAllScheduledNotificationsAsync',
      'getNextTriggerDateAsync',
      'SchedulableTriggerInputTypes',
      'CALENDAR',
      'DAILY',
      'WEEKLY',
      'MONTHLY',
      'YEARLY',
      'DATE',
      'TIME_INTERVAL',
      'getPresentedNotificationsAsync',
      'dismissNotificationAsync',
      'dismissAllNotificationsAsync',
      'subtitle',
      'categoryIdentifier',
      'interruptionLevel',
      'sticky',
      'autoDismiss',
      'vibrate',
      'channelId',
      'repeats',
      'getNotificationChannelsAsync',
      'getNotificationChannelAsync',
      'setNotificationChannelAsync',
      'deleteNotificationChannelAsync',
      'getNotificationChannelGroupsAsync',
      'getNotificationChannelGroupAsync',
      'setNotificationChannelGroupAsync',
      'deleteNotificationChannelGroupAsync',
      'AndroidImportance',
      'AndroidNotificationVisibility',
      'AndroidNotificationPriority',
      'AndroidAudioUsage',
      'AndroidAudioContentType',
      'bypassDnd',
      'lockscreenVisibility',
      'audioAttributes',
      'getNotificationCategoriesAsync',
      'setNotificationCategoryAsync',
      'deleteNotificationCategoryAsync',
      'buttonTitle',
      'textInput',
      'opensAppToForeground',
      'addNotificationReceivedListener',
      'addNotificationResponseReceivedListener',
      'addNotificationResponseClearedListener',
      'addNotificationsDroppedListener',
      'getLastNotificationResponse',
      'getLastNotificationResponseAsync',
      'clearLastNotificationResponse',
      'clearLastNotificationResponseAsync',
      'useLastNotificationResponse',
      'DEFAULT_ACTION_IDENTIFIER',
      'determineNextResponse',
      'IosAuthorizationStatus',
      'IosAlertStyle',
      'IosAllowsPreviews',
      'PermissionStatus',
    ],
  },
];

describe.each(SCREENS)(
  '$route screen',
  ({ route, pkg, surface, parts = [] }) => {
    const screenFile = `screens/${route}Screen.tsx`;
    const source = () =>
      [screenFile, ...parts]
        .filter(file => existsSync(join(APP_DIR, file)))
        .map(read)
        .join('\n');

    it('is a file on disk', () => {
      expect(existsSync(join(APP_DIR, screenFile))).toBe(true);
    });

    it('is a registered route reachable from the menu', () => {
      expect(read('routes.ts')).toContain(`${route}: '${route}'`);
      expect(read('navigation-lines.ts')).toContain(`[ROUTE_NAME.${route}]`);
      // App.tsx renders the rows of screen-registry.ts, so the route is tied to its screen there
      expect(read('screen-registry.ts')).toMatch(
        new RegExp(
          `route: ROUTE_NAME\\.${route},\\s+component: ${route}Screen,`,
        ),
      );
      expect(read('screens/MenuScreen.tsx')).toContain(
        `route: ROUTE_NAME.${route}`,
      );
    });

    it('depends on the package it demos', () => {
      expect(JSON.parse(read('package.json')).dependencies).toHaveProperty(pkg);
    });

    it.each(surface)('exercises %s', name => {
      expect(source()).toMatch(new RegExp(`\\b${name}\\b`));
    });
  },
);
