// Auto-generated by @symbiote-native/css-parser from the matching CSS Modules file.
// Do not edit by hand — regenerate via `css-dts` instead.
declare const styles: {
  readonly "sc-chip-base": string;
  readonly "sc-chip-loud": string;
  readonly "sc-chip-text": string;
  readonly "sc-chip-tinted": string;
  readonly "sc-global-mark": string;
};
export default styles;
