// Forwards every accessibility input and gated event of a wrapper list to the list it renders
// Angular has no attribute spread, and a template must be one static string

export const LIST_ACCESSIBILITY_FORWARD = `
  [accessible]="accessible"
  [accessibilityLabel]="accessibilityLabel"
  [accessibilityHint]="accessibilityHint"
  [accessibilityRole]="accessibilityRole"
  [accessibilityState]="accessibilityState"
  [accessibilityValue]="accessibilityValue"
  [accessibilityActions]="accessibilityActions"
  [accessibilityLabelledBy]="accessibilityLabelledBy"
  [importantForAccessibility]="importantForAccessibility"
  [accessibilityLiveRegion]="accessibilityLiveRegion"
  [screenReaderFocusable]="screenReaderFocusable"
  [accessibilityViewIsModal]="accessibilityViewIsModal"
  [accessibilityElementsHidden]="accessibilityElementsHidden"
  [accessibilityIgnoresInvertColors]="accessibilityIgnoresInvertColors"
  [accessibilityLanguage]="accessibilityLanguage"
  [accessibilityRespondsToUserInteraction]="accessibilityRespondsToUserInteraction"
  [accessibilityShowsLargeContentViewer]="accessibilityShowsLargeContentViewer"
  [accessibilityLargeContentTitle]="accessibilityLargeContentTitle"
  (accessibilityAction)="accessibilityAction.emit($event)"
  (accessibilityTap)="accessibilityTap.emit($event)"
  (magicTap)="magicTap.emit($event)"
  (accessibilityEscape)="accessibilityEscape.emit($event)"
  [role]="role"
  [aria-label]="ariaLabel"
  [aria-labelledby]="ariaLabelledBy"
  [aria-live]="ariaLive"
  [aria-hidden]="ariaHidden"
  [aria-busy]="ariaBusy"
  [aria-checked]="ariaChecked"
  [aria-disabled]="ariaDisabled"
  [aria-expanded]="ariaExpanded"
  [aria-selected]="ariaSelected"
  [aria-modal]="ariaModal"
  [aria-valuemax]="ariaValueMax"
  [aria-valuemin]="ariaValueMin"
  [aria-valuenow]="ariaValueNow"
  [aria-valuetext]="ariaValueText"
`;
