export enum ContactField {
  IS_FAVOURITE = 'isFavourite',
  FULL_NAME = 'fullName',
  GIVEN_NAME = 'givenName',
  MIDDLE_NAME = 'middleName',
  FAMILY_NAME = 'familyName',
  MAIDEN_NAME = 'maidenName',
  NICKNAME = 'nickname',
  PREFIX = 'prefix',
  SUFFIX = 'suffix',
  PHONETIC_GIVEN_NAME = 'phoneticGivenName',
  PHONETIC_MIDDLE_NAME = 'phoneticMiddleName',
  PHONETIC_FAMILY_NAME = 'phoneticFamilyName',
  COMPANY = 'company',
  PHONETIC_COMPANY_NAME = 'phoneticCompanyName',
  DEPARTMENT = 'department',
  JOB_TITLE = 'jobTitle',
  NOTE = 'note',
  IMAGE = 'image',
  THUMBNAIL = 'thumbnail',
  BIRTHDAY = 'birthday',
  NON_GREGORIAN_BIRTHDAY = 'nonGregorianBirthday',
  EMAILS = 'emails',
  PHONES = 'phones',
  ADDRESSES = 'addresses',
  EXTRA_NAMES = 'extraNames',
  DATES = 'dates',
  RELATIONS = 'relations',
  URL_ADDRESSES = 'urlAddresses',
  SOCIAL_PROFILES = 'socialProfiles',
  IM_ADDRESSES = 'imAddresses',
}

export enum ContactsSortOrder {
  UserDefault = 'userDefault',
  GivenName = 'givenName',
  FamilyName = 'familyName',
  None = 'none',
}

/** @platform ios */
export enum NonGregorianCalendar {
  buddhist = 'buddhist',
  chinese = 'chinese',
  coptic = 'coptic',
  ethiopicAmeteMihret = 'ethiopicAmeteMihret',
  ethiopicAmeteAlem = 'ethiopicAmeteAlem',
  hebrew = 'hebrew',
  indian = 'indian',
  islamic = 'islamic',
  islamicCivil = 'islamicCivil',
  japanese = 'japanese',
  persian = 'persian',
  republicOfChina = 'republicOfChina',
}
