'use strict';

const fs = require('node:fs');
const { dlog, warn, applyIfChanged } = require('./common.cjs');
const {
  MAIN_APPLICATION_FILE,
  buildGradlePath,
  rootBuildGradlePath,
  kspLookupPath,
  findMainApplicationFile,
} = require('./android-paths.cjs');

const BEGIN_TAG = 'SYMBIOTE-EXPO-LINK:BEGIN';
const END_TAG = 'SYMBIOTE-EXPO-LINK:END';
const REGION_NOTE = 'generated by symbiote-expo-link - do not edit, regenerated on every install';

const REACT_ANDROID_ANCHOR = 'implementation("com.facebook.react:react-android")';
const MODULES_MAP_ANCHOR = 'override fun getModulesMap(): Map<Class<out Module>, String?> = mapOf(';
// В рукописном `ExpoModulesProvider` заглушки `getServices()` нет (`AppContext` отдаёт
// `emptyList()`), поэтому метод целиком генерируется и якорится сразу после открытия класса
const MODULES_PROVIDER_CLASS_ANCHOR = ': ModulesProvider {';
const SERVICE_IMPORT = 'import expo.modules.kotlin.services.Service';

// undefined: региона нет, null: потерян конец и предупреждение уже выдано
// Угадывание конца полустёртого региона съело бы код разработчика
function locateRegion(lines, name, filePath) {
  const begin = lines.findIndex((line) => line.includes(`${BEGIN_TAG} ${name}`));
  if (begin === -1) return undefined;
  const end = lines.findIndex((line, i) => i > begin && line.includes(`${END_TAG} ${name}`));
  if (end === -1) {
    warn(
      `${filePath} has "${BEGIN_TAG} ${name}" but no matching "${END_TAG} ${name}". ` +
        'Restore the end marker (or delete the whole block) and reinstall.',
    );
    return null;
  }
  return { begin, end };
}

// Владение всем регионом, а не дописывание строк, даёт записи удалённого пакета исчезнуть
// Возвращает null с уже выданным предупреждением: полустёртый регион и потерянный якорь
// чинятся по-разному
function writeRegion({ filePath, content, name, indent, bodyLines, findAnchorIndex, anchorLabel }) {
  const lines = content.split('\n');
  const block = [
    `${indent}// ${BEGIN_TAG} ${name} (${REGION_NOTE})`,
    ...bodyLines.map((line) => `${indent}${line}`),
    `${indent}// ${END_TAG} ${name}`,
  ];

  const region = locateRegion(lines, name, filePath);
  if (region === null) return null;
  if (region !== undefined) {
    lines.splice(region.begin, region.end - region.begin + 1, ...block);
    return lines.join('\n');
  }

  const anchorIndex = findAnchorIndex(lines);
  if (anchorIndex === -1) {
    warn(`cannot create the ${name} block in ${filePath}: ${anchorLabel}`);
    return null;
  }
  lines.splice(anchorIndex + 1, 0, ...block);
  return lines.join('\n');
}

function androidModulesOf(entries) {
  return entries.flatMap((entry) =>
    entry.manifest.android && Array.isArray(entry.manifest.android.modules) ? entry.manifest.android.modules : [],
  );
}

function androidServicesOf(entries) {
  return entries.flatMap((entry) =>
    entry.manifest.android && Array.isArray(entry.manifest.android.services) ? entry.manifest.android.services : [],
  );
}

function patchBuildGradle(appRoot, entries) {
  const gradlePath = buildGradlePath(appRoot);
  if (!fs.existsSync(gradlePath)) {
    dlog('android/app/build.gradle not found, skipping');
    return;
  }

  const primaryProjectNames = entries
    .filter((entry) => entry.manifest.android && entry.manifest.android.gradleProjectName)
    .map((entry) => entry.manifest.android.gradleProjectName);
  // Запись `services` может опираться на другой нативный пакет, чем объявивший её (список
  // task-manager ссылается на `ConstantsService` из expo-constants), его подпроект тоже нужен
  const serviceProjectNames = androidServicesOf(entries).map((service) => service.gradleProjectName);
  const deps = [...new Set([...primaryProjectNames, ...serviceProjectNames])]
    .sort()
    .map((name) => `implementation project(':${name}')`);

  const content = fs.readFileSync(gradlePath, 'utf8');
  const next = writeRegion({
    filePath: gradlePath,
    content,
    name: 'DEPENDENCIES',
    indent: '    ',
    bodyLines: deps,
    findAnchorIndex: (lines) => lines.findIndex((line) => line.includes(REACT_ANDROID_ANCHOR)),
    anchorLabel: `no \`${REACT_ANDROID_ANCHOR}\` line to anchor below`,
  });
  applyIfChanged(gradlePath, content, next);
}

// Тот же регион, но наружу: нужен, когда ни один пакет его больше не требует
// null при потерянном конце региона, предупреждение уже выдано
function removeRegion(content, name, filePath) {
  const lines = content.split('\n');
  const region = locateRegion(lines, name, filePath);
  if (region === null) return null;
  if (region === undefined) return content;
  lines.splice(region.begin, region.end - region.begin + 1);
  return lines.join('\n');
}

const KOTLIN_VERSION_PATTERN = /^\s*kotlinVersion\s*=\s*"([^"]+)"/;
const KSP_VERSION_PATTERN = /\bkspVersion\b/;
const KSP_PAIR_PATTERN = /"([^"]+)"\s+to\s+"([^"]+)"/g;
const LATEST_KSP_PATTERN = /latestKspVersion\s*=\s*"([^"]+)"/;
// С Kotlin 2.3.0 версия KSP от Kotlin не зависит, Expo берёт в этом случае `latestKspVersion`
const KSP_UNTIED_FROM_KOTLIN = [2, 3];

function isKotlinAtLeast(version, [major, minor]) {
  const [versionMajor, versionMinor] = version.split('.').map((part) => parseInt(part, 10) || 0);
  return versionMajor > major || (versionMajor === major && versionMinor >= minor);
}

// Тот же выбор, что у `ExpoRootProjectPlugin`: пара из таблицы, иначе последняя для нового Kotlin
// null с предупреждением, когда выбрать нечего: гадать версию KSP нельзя, она ломает сборку модулей
function resolveKspVersion(appRoot, kotlinVersion, gradlePath) {
  const lookupPath = kspLookupPath(appRoot);
  const byHand = `Set kspVersion in ${gradlePath} by hand.`;
  if (!fs.existsSync(lookupPath)) {
    warn(`cannot read ${lookupPath} to pick the KSP build for Kotlin ${kotlinVersion}. ${byHand}`);
    return null;
  }

  const source = fs.readFileSync(lookupPath, 'utf8');
  const table = new Map([...source.matchAll(KSP_PAIR_PATTERN)].map((pair) => [pair[1], pair[2]]));
  const latest = LATEST_KSP_PATTERN.exec(source);
  const version = table.get(kotlinVersion) ?? (isKotlinAtLeast(kotlinVersion, KSP_UNTIED_FROM_KOTLIN) && latest ? latest[1] : null);
  if (version === null) warn(`Kotlin ${kotlinVersion} has no KSP build in Expo's KSPLookup.kt. ${byHand}`);
  return version;
}

// `kspVersion` читают `expo-image` и `expo-app-metrics` из корневого проекта, а версия зависит
// от Kotlin приложения, поэтому её считаем здесь, а не пишем в `native-link.json` пакета
function patchRootBuildGradle(appRoot, entries) {
  const gradlePath = rootBuildGradlePath(appRoot);
  if (!fs.existsSync(gradlePath)) {
    dlog('android/build.gradle not found, skipping');
    return;
  }

  const content = fs.readFileSync(gradlePath, 'utf8');
  const isRequired = entries.some((entry) => entry.manifest.android && entry.manifest.android.requiresKsp === true);
  const withoutRegion = removeRegion(content, 'KSP', gradlePath);
  if (withoutRegion === null) return;
  // Рукописный `kspVersion` разработчика главнее, второе определение рядом с ним только путает
  if (!isRequired || KSP_VERSION_PATTERN.test(withoutRegion)) {
    applyIfChanged(gradlePath, content, withoutRegion);
    return;
  }

  const lines = content.split('\n');
  const anchorIndex = lines.findIndex((line) => KOTLIN_VERSION_PATTERN.test(line));
  if (anchorIndex === -1) {
    warn(`cannot create the KSP block in ${gradlePath}: no \`kotlinVersion = "..."\` line to read the Kotlin version from`);
    return;
  }
  const kotlinVersion = KOTLIN_VERSION_PATTERN.exec(lines[anchorIndex])[1];
  const kspVersion = resolveKspVersion(appRoot, kotlinVersion, gradlePath);
  if (kspVersion === null) return;

  const next = writeRegion({
    filePath: gradlePath,
    content,
    name: 'KSP',
    indent: /^\s*/.exec(lines[anchorIndex])[0],
    bodyLines: [`kspVersion = "${kspVersion}"`],
    findAnchorIndex: (current) => current.findIndex((line) => KOTLIN_VERSION_PATTERN.test(line)),
    anchorLabel: 'no `kotlinVersion = "..."` line to anchor below',
  });
  applyIfChanged(gradlePath, content, next);
}

// Якорь под ПОСЛЕДНИМ импортом: Kotlin требует импорты выше первого объявления,
// а рукописные остаются там, где их поставил разработчик
function lastImportIndex(lines) {
  return lines.reduce((last, line, i) => (line.trim().startsWith('import ') ? i : last), -1);
}

function mainApplicationImports(modules, services) {
  return [
    ...new Set([
      ...modules.map((module) => `import ${module.importPath}`),
      ...services.map((service) => `import ${service.importPath}`),
      // Нужен только возвращаемому типу `getServices()`, но метод всегда регенерируется целиком
      SERVICE_IMPORT,
    ]),
  ].sort();
}

function patchMainApplication(appRoot, entries) {
  const filePath = findMainApplicationFile(appRoot);
  if (!filePath) {
    dlog(`${MAIN_APPLICATION_FILE} not found, skipping`);
    return;
  }

  const modules = androidModulesOf(entries);
  const services = androidServicesOf(entries);
  const mapEntries = [...new Set(modules.map((module) => `${module.className}::class.java to "${module.nativeName}",`))].sort();
  const serviceEntries = [...new Set(services.map((service) => `  ${service.className}::class.java,`))].sort();
  const content = fs.readFileSync(filePath, 'utf8');

  const withImports = writeRegion({
    filePath,
    content,
    name: 'IMPORTS',
    indent: '',
    bodyLines: mainApplicationImports(modules, services),
    findAnchorIndex: lastImportIndex,
    anchorLabel: 'no import statements to anchor below',
  });
  if (withImports === null) return;

  const withModules = writeRegion({
    filePath,
    content: withImports,
    name: 'MODULES-MAP',
    indent: '    ',
    bodyLines: mapEntries,
    findAnchorIndex: (lines) => lines.findIndex((line) => line.includes(MODULES_MAP_ANCHOR)),
    anchorLabel: 'no `getModulesMap()` declaration to anchor below',
  });
  if (withModules === null) return;

  const next = writeRegion({
    filePath,
    content: withModules,
    name: 'SERVICES',
    indent: '  ',
    bodyLines: ['override fun getServices(): List<Class<out Service>> = listOf(', ...serviceEntries, ')'],
    findAnchorIndex: (lines) => lines.findIndex((line) => line.includes(MODULES_PROVIDER_CLASS_ANCHOR)),
    anchorLabel: 'no `ExpoModulesProvider : ModulesProvider` class declaration to anchor below',
  });
  applyIfChanged(filePath, content, next);
}

module.exports = { androidServicesOf, patchBuildGradle, patchRootBuildGradle, patchMainApplication };
