'use strict';

const fs = require('node:fs');
const path = require('node:path');

// One process per app: scan node_modules, regenerate the registration blocks from what's
// installed. Same approach as expo-modules-autolinking.
//
// Do NOT move this back into each wrapper package's own postinstall. Package managers run those
// concurrently, and N processes doing read-modify-write on one build.gradle silently lose
// entries; a correct lock is not reachable from plain `fs` (no compare-and-unlink, no flock).
// Full history in the README under "Why an aggregator".
const BEGIN_TAG = 'SYMBIOTE-EXPO-LINK:BEGIN';
const END_TAG = 'SYMBIOTE-EXPO-LINK:END';
const REGION_NOTE = 'generated by symbiote-expo-link - do not edit, regenerated on every install';

const REACT_ANDROID_ANCHOR = 'implementation("com.facebook.react:react-android")';
const MODULES_MAP_ANCHOR = 'override fun getModulesMap(): Map<Class<out Module>, String?> = mapOf(';

const MANIFEST_FILENAME = 'native-link.json';

function isDebug() {
  return process.env.DEBUG === '1' || process.env.DEBUG === 'true' || globalThis.__SYMBIOTE_DEBUG__ === true;
}

function dlog(...args) {
  if (isDebug()) console.log('[symbiote-expo-link]', ...args);
}

// Never gated, unlike dlog: an unreachable native file or a drifting description is something
// the developer has to act on, and the alternative is finding out at runtime.
function warn(message) {
  console.warn(`[symbiote-expo-link] ${message}`);
}

// Ctrl-C mid-writeFileSync truncates the target in place, and these are committed Xcode/Gradle
// projects, not rebuildable scaffolding. Temp file + rename is atomic on POSIX (same filesystem,
// same directory): fully replaced or untouched.
function writeFileAtomic(filePath, content) {
  const tmpPath = `${filePath}.symbiote-expo-link.${process.pid}.tmp`;
  fs.writeFileSync(tmpPath, content);
  fs.renameSync(tmpPath, filePath);
}

// cwd is already the app root for an app-level postinstall. INIT_CWD (npm sets it to wherever
// the install was invoked) is the fallback for being run as a nested lifecycle script instead.
// Neither walks up, so running this from a subdirectory of the app finds nothing.
function findAppRoot() {
  const candidates = [process.cwd(), process.env.INIT_CWD].filter(Boolean);
  for (const candidate of candidates) {
    if (fs.existsSync(path.join(candidate, 'android', 'app', 'build.gradle'))) return candidate;
    if (findInfoPlistFile(candidate)) return candidate;
  }
  return null;
}

// The app's own Info.plist, never a Pod's/framework's/test target's - those all carry the same
// filename. RN's default template puts it at ios/<AppName>/Info.plist; excluding
// Pods/build/DerivedData/*Tests* leaves exactly that one in every app this package has seen.
function findInfoPlistFile(appRoot) {
  const iosRoot = path.join(appRoot, 'ios');
  if (!fs.existsSync(iosRoot)) return null;
  const skip = /Pods|build|DerivedData|Tests/i;
  const stack = [iosRoot];
  while (stack.length > 0) {
    const dir = stack.pop();
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      if (skip.test(entry.name)) continue;
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) stack.push(full);
      else if (entry.name === 'Info.plist') return full;
    }
  }
  return null;
}

function findMainApplicationFile(appRoot) {
  const javaRoot = path.join(appRoot, 'android', 'app', 'src', 'main', 'java');
  if (!fs.existsSync(javaRoot)) return null;
  const stack = [javaRoot];
  while (stack.length > 0) {
    const dir = stack.pop();
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) stack.push(full);
      else if (entry.name === 'MainApplication.kt') return full;
    }
  }
  return null;
}

function readManifest(packageDir, packageName) {
  const manifestPath = path.join(packageDir, MANIFEST_FILENAME);
  // existsSync follows symlinks, which is what pnpm's node_modules and a workspace link both are.
  if (!fs.existsSync(manifestPath)) return null;
  try {
    return { packageName, manifest: JSON.parse(fs.readFileSync(manifestPath, 'utf8')) };
  } catch (error) {
    warn(`skipping ${packageName}: its ${MANIFEST_FILENAME} is not valid JSON (${error.message})`);
    return null;
  }
}

// Sorted by package name so the generated blocks come out byte-identical across machines:
// readdir order varies, and these blocks live in committed native files.
function collectManifests(appRoot) {
  const modulesRoot = path.join(appRoot, 'node_modules');
  if (!fs.existsSync(modulesRoot)) {
    warn(`no node_modules in ${appRoot}, nothing to link`);
    return [];
  }

  const found = [];
  for (const entry of fs.readdirSync(modulesRoot, { withFileTypes: true })) {
    if (entry.name.startsWith('.')) continue;

    if (entry.name.startsWith('@')) {
      const scopeDir = path.join(modulesRoot, entry.name);
      for (const scoped of fs.readdirSync(scopeDir, { withFileTypes: true })) {
        const entryFound = readManifest(path.join(scopeDir, scoped.name), `${entry.name}/${scoped.name}`);
        if (entryFound) found.push(entryFound);
      }
      continue;
    }

    const entryFound = readManifest(path.join(modulesRoot, entry.name), entry.name);
    if (entryFound) found.push(entryFound);
  }

  found.sort((a, b) => (a.packageName < b.packageName ? -1 : a.packageName > b.packageName ? 1 : 0));
  dlog(`found ${found.length} linkable package(s): ${found.map((f) => f.packageName).join(', ')}`);
  return found;
}

// Owning a whole region rather than appending lines is what lets an uninstalled package's entry
// disappear. Returns null (already warned) when it can't write: a half-deleted region and a
// missing anchor need different fixes, so each reports its own cause.
function writeRegion({ filePath, content, name, indent, bodyLines, findAnchorIndex, anchorLabel }) {
  const lines = content.split('\n');
  const block = [
    `${indent}// ${BEGIN_TAG} ${name} (${REGION_NOTE})`,
    ...bodyLines.map((line) => `${indent}${line}`),
    `${indent}// ${END_TAG} ${name}`,
  ];

  const beginIndex = lines.findIndex((line) => line.includes(`${BEGIN_TAG} ${name}`));
  if (beginIndex !== -1) {
    const endIndex = lines.findIndex((line, i) => i > beginIndex && line.includes(`${END_TAG} ${name}`));
    if (endIndex === -1) {
      // Guessing where a half-deleted region ends would eat the developer's code.
      warn(
        `${filePath} has "${BEGIN_TAG} ${name}" but no matching "${END_TAG} ${name}". ` +
          'Restore the end marker (or delete the whole block) and reinstall.',
      );
      return null;
    }
    lines.splice(beginIndex, endIndex - beginIndex + 1, ...block);
    return lines.join('\n');
  }

  const anchorIndex = findAnchorIndex(lines);
  if (anchorIndex === -1) {
    warn(`cannot create the ${name} block in ${filePath}: ${anchorLabel}`);
    return null;
  }
  lines.splice(anchorIndex + 1, 0, ...block);
  return lines.join('\n');
}

function applyIfChanged(filePath, content, nextContent) {
  if (nextContent === null || nextContent === content) return;
  writeFileAtomic(filePath, nextContent);
  dlog(`updated ${filePath}`);
}

function patchBuildGradle(appRoot, entries) {
  const gradlePath = path.join(appRoot, 'android', 'app', 'build.gradle');
  if (!fs.existsSync(gradlePath)) {
    dlog('android/app/build.gradle not found, skipping');
    return;
  }

  const projectNames = entries
    .filter((entry) => entry.manifest.android && entry.manifest.android.gradleProjectName)
    .map((entry) => entry.manifest.android.gradleProjectName);
  const deps = [...new Set(projectNames)].sort().map((name) => `implementation project(':${name}')`);

  const content = fs.readFileSync(gradlePath, 'utf8');
  const next = writeRegion({
    filePath: gradlePath,
    content,
    name: 'DEPENDENCIES',
    indent: '    ',
    bodyLines: deps,
    findAnchorIndex: (lines) => lines.findIndex((line) => line.includes(REACT_ANDROID_ANCHOR)),
    anchorLabel: `no \`${REACT_ANDROID_ANCHOR}\` line to anchor below`,
  });
  applyIfChanged(gradlePath, content, next);
}

function androidModulesOf(entries) {
  return entries.flatMap((entry) =>
    entry.manifest.android && Array.isArray(entry.manifest.android.modules) ? entry.manifest.android.modules : [],
  );
}

function patchMainApplication(appRoot, entries) {
  const filePath = findMainApplicationFile(appRoot);
  if (!filePath) {
    dlog('MainApplication.kt not found, skipping');
    return;
  }

  const modules = androidModulesOf(entries);
  const imports = [...new Set(modules.map((module) => `import ${module.importPath}`))].sort();
  const mapEntries = [...new Set(modules.map((module) => `${module.className}::class.java to "${module.nativeName}",`))].sort();

  const content = fs.readFileSync(filePath, 'utf8');

  // Anchored below the LAST import: Kotlin requires imports above the first declaration, and
  // going last leaves hand-written ones where the developer put them.
  const withImports = writeRegion({
    filePath,
    content,
    name: 'IMPORTS',
    indent: '',
    bodyLines: imports,
    findAnchorIndex: (lines) => {
      let lastImport = -1;
      for (let i = 0; i < lines.length; i += 1) {
        if (lines[i].trim().startsWith('import ')) lastImport = i;
      }
      return lastImport;
    },
    anchorLabel: 'no import statements to anchor below',
  });
  if (withImports === null) return;

  const next = writeRegion({
    filePath,
    content: withImports,
    name: 'MODULES-MAP',
    indent: '    ',
    bodyLines: mapEntries,
    findAnchorIndex: (lines) => lines.findIndex((line) => line.includes(MODULES_MAP_ANCHOR)),
    anchorLabel: 'no `getModulesMap()` declaration to anchor below',
  });
  applyIfChanged(filePath, content, next);
}

// An "&" or "<" in a description would otherwise produce a plist that no longer parses. A text
// node needs only these three; quotes and apostrophes are legal as-is.
function escapeXml(value) {
  return String(value).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function readPlistString(content, key) {
  const keyIndex = content.indexOf(`<key>${key}</key>`);
  if (keyIndex === -1) return null;
  const match = /<string>([\s\S]*?)<\/string>/.exec(content.slice(keyIndex));
  return match ? match[1] : null;
}

// No generated region here, unlike the Android files: Xcode rewrites Info.plist through its own
// serializer whenever target settings change, and that serializer drops XML comments. A lost END
// marker would make the next run insert a second block, producing duplicate keys and an invalid
// plist. So iOS stays additive, with `<key>NAME</key>` presence as the idempotency check.
//
// That means an existing key's VALUE is never overwritten. Intended: a description is
// user-facing App Store copy, so a hand-edit outranks a package default. Drift would then go
// unnoticed, hence the warning.
function patchInfoPlist(appRoot, entries) {
  const wanted = new Map();
  for (const entry of entries) {
    const keys = entry.manifest.ios && entry.manifest.ios.infoPlistKeys;
    if (!keys) continue;
    for (const [key, description] of Object.entries(keys)) {
      if (!wanted.has(key)) wanted.set(key, description);
    }
  }
  if (wanted.size === 0) return;

  const plistPath = findInfoPlistFile(appRoot);
  if (!plistPath) {
    dlog('Info.plist not found, skipping iOS permission strings');
    return;
  }

  const content = fs.readFileSync(plistPath, 'utf8');
  let next = content;

  for (const [key, description] of [...wanted].sort((a, b) => (a[0] < b[0] ? -1 : 1))) {
    const escaped = escapeXml(description);
    const existing = readPlistString(next, key);

    if (existing !== null) {
      if (existing !== escaped) {
        warn(
          `${key} in ${plistPath} reads "${existing}" but the package manifest says ` +
            `"${description}". Keeping the file as-is; edit it by hand if you want the manifest's.`,
        );
      }
      continue;
    }

    const plistCloseIndex = next.lastIndexOf('</plist>');
    const dictCloseIndex = next.lastIndexOf('</dict>', plistCloseIndex === -1 ? undefined : plistCloseIndex);
    if (dictCloseIndex === -1) {
      warn(`${plistPath} has no closing </dict>, skipping ${key}`);
      continue;
    }

    const block = `\t<key>${key}</key>\n\t<string>${escaped}</string>\n`;
    next = next.slice(0, dictCloseIndex) + block + next.slice(dictCloseIndex);
  }

  applyIfChanged(plistPath, content, next);
}

// Safe to run any number of times, and after an uninstall.
function linkApp(explicitAppRoot) {
  const appRoot = explicitAppRoot || findAppRoot();
  if (!appRoot) {
    warn('no React Native app here (no android/app/build.gradle, no ios/**/Info.plist), skipping');
    return;
  }

  const entries = collectManifests(appRoot);
  patchBuildGradle(appRoot, entries);
  patchMainApplication(appRoot, entries);
  patchInfoPlist(appRoot, entries);
}

module.exports = {
  linkApp,
  collectManifests,
  findAppRoot,
  findInfoPlistFile,
  findMainApplicationFile,
  patchBuildGradle,
  patchMainApplication,
  patchInfoPlist,
};
