'use strict';

const fs = require('node:fs');
const path = require('node:path');

// One process per app: scan node_modules, regenerate the registration blocks from what's
// installed. Same approach as expo-modules-autolinking.
//
// Do NOT move this back into each wrapper package's own postinstall. Package managers run those
// concurrently, and N processes doing read-modify-write on one build.gradle silently lose
// entries; a correct lock is not reachable from plain `fs` (no compare-and-unlink, no flock).
// Full history in the README under "Why an aggregator".
const BEGIN_TAG = 'SYMBIOTE-EXPO-LINK:BEGIN';
const END_TAG = 'SYMBIOTE-EXPO-LINK:END';
const REGION_NOTE = 'generated by symbiote-expo-link - do not edit, regenerated on every install';

const REACT_ANDROID_ANCHOR = 'implementation("com.facebook.react:react-android")';
const MODULES_MAP_ANCHOR = 'override fun getModulesMap(): Map<Class<out Module>, String?> = mapOf(';

const MANIFEST_FILENAME = 'native-link.json';

function isDebug() {
  return process.env.DEBUG === '1' || process.env.DEBUG === 'true' || globalThis.__SYMBIOTE_DEBUG__ === true;
}

function dlog(...args) {
  if (isDebug()) console.log('[symbiote-expo-link]', ...args);
}

// Never gated, unlike dlog: an unreachable native file or a drifting description is something
// the developer has to act on, and the alternative is finding out at runtime.
function warn(message) {
  console.warn(`[symbiote-expo-link] ${message}`);
}

// Ctrl-C mid-writeFileSync truncates the target in place, and these are committed Xcode/Gradle
// projects, not rebuildable scaffolding. Temp file + rename is atomic on POSIX (same filesystem,
// same directory): fully replaced or untouched.
function writeFileAtomic(filePath, content) {
  const tmpPath = `${filePath}.symbiote-expo-link.${process.pid}.tmp`;
  fs.writeFileSync(tmpPath, content);
  fs.renameSync(tmpPath, filePath);
}

// cwd is already the app root for an app-level postinstall. INIT_CWD (npm sets it to wherever
// the install was invoked) is the fallback for being run as a nested lifecycle script instead.
// Neither walks up, so running this from a subdirectory of the app finds nothing.
function findAppRoot() {
  const candidates = [process.cwd(), process.env.INIT_CWD].filter(Boolean);
  for (const candidate of candidates) {
    if (fs.existsSync(path.join(candidate, 'android', 'app', 'build.gradle'))) return candidate;
    if (findInfoPlistFile(candidate)) return candidate;
  }
  return null;
}

// The app's own Info.plist, never a Pod's/framework's/test target's - those all carry the same
// filename. RN's default template puts it at ios/<AppName>/Info.plist; excluding
// Pods/build/DerivedData/*Tests* leaves exactly that one in every app this package has seen.
function findInfoPlistFile(appRoot) {
  const iosRoot = path.join(appRoot, 'ios');
  if (!fs.existsSync(iosRoot)) return null;
  const skip = /Pods|build|DerivedData|Tests/i;
  const stack = [iosRoot];
  while (stack.length > 0) {
    const dir = stack.pop();
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      if (skip.test(entry.name)) continue;
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) stack.push(full);
      else if (entry.name === 'Info.plist') return full;
    }
  }
  return null;
}

function findMainApplicationFile(appRoot) {
  const javaRoot = path.join(appRoot, 'android', 'app', 'src', 'main', 'java');
  if (!fs.existsSync(javaRoot)) return null;
  const stack = [javaRoot];
  while (stack.length > 0) {
    const dir = stack.pop();
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) stack.push(full);
      else if (entry.name === 'MainApplication.kt') return full;
    }
  }
  return null;
}

function readManifest(packageDir, packageName) {
  const manifestPath = path.join(packageDir, MANIFEST_FILENAME);
  // existsSync follows symlinks, which is what pnpm's node_modules and a workspace link both are.
  if (!fs.existsSync(manifestPath)) return null;
  try {
    return { packageName, manifest: JSON.parse(fs.readFileSync(manifestPath, 'utf8')) };
  } catch (error) {
    warn(`skipping ${packageName}: its ${MANIFEST_FILENAME} is not valid JSON (${error.message})`);
    return null;
  }
}

// Sorted by package name so the generated blocks come out byte-identical across machines:
// readdir order varies, and these blocks live in committed native files.
function collectManifests(appRoot) {
  const modulesRoot = path.join(appRoot, 'node_modules');
  if (!fs.existsSync(modulesRoot)) {
    warn(`no node_modules in ${appRoot}, nothing to link`);
    return [];
  }

  const found = [];
  for (const entry of fs.readdirSync(modulesRoot, { withFileTypes: true })) {
    if (entry.name.startsWith('.')) continue;

    if (entry.name.startsWith('@')) {
      const scopeDir = path.join(modulesRoot, entry.name);
      for (const scoped of fs.readdirSync(scopeDir, { withFileTypes: true })) {
        const entryFound = readManifest(path.join(scopeDir, scoped.name), `${entry.name}/${scoped.name}`);
        if (entryFound) found.push(entryFound);
      }
      continue;
    }

    const entryFound = readManifest(path.join(modulesRoot, entry.name), entry.name);
    if (entryFound) found.push(entryFound);
  }

  found.sort((a, b) => (a.packageName < b.packageName ? -1 : a.packageName > b.packageName ? 1 : 0));
  dlog(`found ${found.length} linkable package(s): ${found.map((f) => f.packageName).join(', ')}`);
  return found;
}

// Owning a whole region rather than appending lines is what lets an uninstalled package's entry
// disappear. Returns null (already warned) when it can't write: a half-deleted region and a
// missing anchor need different fixes, so each reports its own cause.
function writeRegion({ filePath, content, name, indent, bodyLines, findAnchorIndex, anchorLabel }) {
  const lines = content.split('\n');
  const block = [
    `${indent}// ${BEGIN_TAG} ${name} (${REGION_NOTE})`,
    ...bodyLines.map((line) => `${indent}${line}`),
    `${indent}// ${END_TAG} ${name}`,
  ];

  const beginIndex = lines.findIndex((line) => line.includes(`${BEGIN_TAG} ${name}`));
  if (beginIndex !== -1) {
    const endIndex = lines.findIndex((line, i) => i > beginIndex && line.includes(`${END_TAG} ${name}`));
    if (endIndex === -1) {
      // Guessing where a half-deleted region ends would eat the developer's code.
      warn(
        `${filePath} has "${BEGIN_TAG} ${name}" but no matching "${END_TAG} ${name}". ` +
          'Restore the end marker (or delete the whole block) and reinstall.',
      );
      return null;
    }
    lines.splice(beginIndex, endIndex - beginIndex + 1, ...block);
    return lines.join('\n');
  }

  const anchorIndex = findAnchorIndex(lines);
  if (anchorIndex === -1) {
    warn(`cannot create the ${name} block in ${filePath}: ${anchorLabel}`);
    return null;
  }
  lines.splice(anchorIndex + 1, 0, ...block);
  return lines.join('\n');
}

function applyIfChanged(filePath, content, nextContent) {
  if (nextContent === null || nextContent === content) return;
  writeFileAtomic(filePath, nextContent);
  dlog(`updated ${filePath}`);
}

function patchBuildGradle(appRoot, entries) {
  const gradlePath = path.join(appRoot, 'android', 'app', 'build.gradle');
  if (!fs.existsSync(gradlePath)) {
    dlog('android/app/build.gradle not found, skipping');
    return;
  }

  const projectNames = entries
    .filter((entry) => entry.manifest.android && entry.manifest.android.gradleProjectName)
    .map((entry) => entry.manifest.android.gradleProjectName);
  const deps = [...new Set(projectNames)].sort().map((name) => `implementation project(':${name}')`);

  const content = fs.readFileSync(gradlePath, 'utf8');
  const next = writeRegion({
    filePath: gradlePath,
    content,
    name: 'DEPENDENCIES',
    indent: '    ',
    bodyLines: deps,
    findAnchorIndex: (lines) => lines.findIndex((line) => line.includes(REACT_ANDROID_ANCHOR)),
    anchorLabel: `no \`${REACT_ANDROID_ANCHOR}\` line to anchor below`,
  });
  applyIfChanged(gradlePath, content, next);
}

function androidModulesOf(entries) {
  return entries.flatMap((entry) =>
    entry.manifest.android && Array.isArray(entry.manifest.android.modules) ? entry.manifest.android.modules : [],
  );
}

function patchMainApplication(appRoot, entries) {
  const filePath = findMainApplicationFile(appRoot);
  if (!filePath) {
    dlog('MainApplication.kt not found, skipping');
    return;
  }

  const modules = androidModulesOf(entries);
  const imports = [...new Set(modules.map((module) => `import ${module.importPath}`))].sort();
  const mapEntries = [...new Set(modules.map((module) => `${module.className}::class.java to "${module.nativeName}",`))].sort();

  const content = fs.readFileSync(filePath, 'utf8');

  // Anchored below the LAST import: Kotlin requires imports above the first declaration, and
  // going last leaves hand-written ones where the developer put them.
  const withImports = writeRegion({
    filePath,
    content,
    name: 'IMPORTS',
    indent: '',
    bodyLines: imports,
    findAnchorIndex: (lines) => {
      let lastImport = -1;
      for (let i = 0; i < lines.length; i += 1) {
        if (lines[i].trim().startsWith('import ')) lastImport = i;
      }
      return lastImport;
    },
    anchorLabel: 'no import statements to anchor below',
  });
  if (withImports === null) return;

  const next = writeRegion({
    filePath,
    content: withImports,
    name: 'MODULES-MAP',
    indent: '    ',
    bodyLines: mapEntries,
    findAnchorIndex: (lines) => lines.findIndex((line) => line.includes(MODULES_MAP_ANCHOR)),
    anchorLabel: 'no `getModulesMap()` declaration to anchor below',
  });
  applyIfChanged(filePath, content, next);
}

// An "&" or "<" in a description would otherwise produce a plist that no longer parses. A text
// node needs only these three; quotes and apostrophes are legal as-is.
function escapeXml(value) {
  return String(value).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

// Inside a double-quoted attribute the quote itself also has to go, or it closes the value early.
function escapeXmlAttribute(value) {
  return escapeXml(value).replace(/"/g, '&quot;');
}

// The bounds of a `<tagName ...>` opening tag. Scanning for the first unquoted ">" rather than
// matching a regex: RN's own template puts "${usesCleartextTraffic}" in an attribute, and a
// manifest is free to put a ">" inside one.
function findTag(content, tagName) {
  const match = new RegExp(`<${tagName}(?=[\\s>/])`).exec(content);
  if (!match) return null;

  let quote = null;
  for (let i = match.index; i < content.length; i += 1) {
    const char = content[i];
    if (quote !== null) {
      if (char === quote) quote = null;
      continue;
    }
    if (char === '"' || char === "'") quote = char;
    else if (char === '>') return { start: match.index, end: i };
  }
  return null;
}

function findApplicationTag(content) {
  return findTag(content, 'application');
}

function readXmlAttribute(tagText, name) {
  const match = new RegExp(`\\s${name}\\s*=\\s*"([^"]*)"`).exec(tagText);
  return match ? match[1] : null;
}

// Attributes on the app's own `<application>` element, for packages whose Android side needs one
// (secure-store's Auto Backup exclusion rules). Additive-only with the same reasoning as
// Info.plist: an XML attribute is unique per element by construction, so presence is a sufficient
// idempotency check, and no comment can live inside a tag to delimit a region anyway.
function patchAndroidManifest(appRoot, entries) {
  const wanted = new Map();
  for (const entry of entries) {
    const attributes = entry.manifest.android && entry.manifest.android.manifestApplicationAttributes;
    if (!attributes) continue;
    for (const [name, value] of Object.entries(attributes)) {
      if (!wanted.has(name)) wanted.set(name, value);
    }
  }
  if (wanted.size === 0) return;

  const manifestPath = path.join(appRoot, 'android', 'app', 'src', 'main', 'AndroidManifest.xml');
  if (!fs.existsSync(manifestPath)) {
    dlog('AndroidManifest.xml not found, skipping application attributes');
    return;
  }

  const content = fs.readFileSync(manifestPath, 'utf8');
  let next = content;

  for (const [name, value] of [...wanted].sort((a, b) => (a[0] < b[0] ? -1 : 1))) {
    // A metacharacter would slip past readXmlAttribute and we'd append a duplicate attribute,
    // which is an XML parse error rather than a bad value.
    if (!/^[\w.:-]+$/.test(name)) {
      warn(`skipping the manifest attribute "${name}": not a plain XML attribute name`);
      continue;
    }

    const tag = findApplicationTag(next);
    if (!tag) {
      warn(`${manifestPath} has no <application> element, skipping ${name}`);
      return;
    }

    const tagText = next.slice(tag.start, tag.end);
    const escaped = escapeXmlAttribute(value);
    const existing = readXmlAttribute(tagText, name);

    if (existing !== null) {
      if (existing !== escaped) {
        warn(
          `${name} in ${manifestPath} reads "${existing}" but the package manifest says ` +
            `"${value}". Keeping the file as-is; edit it by hand if you want the manifest's.`,
        );
      }
      continue;
    }

    // Follow the indentation of whichever attribute currently sits last, so the tag keeps the
    // shape the developer (or the RN template) gave it.
    const lastNewline = tagText.lastIndexOf('\n');
    const separator = lastNewline === -1 ? ' ' : `\n${/^[ \t]*/.exec(tagText.slice(lastNewline + 1))[0]}`;
    const insertAt = next[tag.end - 1] === '/' ? tag.end - 1 : tag.end;
    next = `${next.slice(0, insertAt)}${separator}${name}="${escaped}"${next.slice(insertAt)}`;
  }

  applyIfChanged(manifestPath, content, next);
}

function readManifestPermissions(content) {
  return new Set([...content.matchAll(/<uses-permission\s[^>]*android:name="([^"]+)"/g)].map((match) => match[1]));
}

// Sibling of patchAndroidManifest for root-level `<uses-permission>` elements rather than
// `<application>` attributes. Same additive policy: an existing permission, however it got there,
// is left alone - this only ever ADDS a missing one, right after the `<manifest>` tag opens.
//
// Every entry here is something the PACKAGE'S OWN AndroidManifest.xml deliberately does NOT
// carry, so autolinking's ordinary merge never adds it - typically because requesting it triggers
// Play Console policy review for every consumer (FOREGROUND_SERVICE_LOCATION,
// FOREGROUND_SERVICE_MICROPHONE, ACCESS_BACKGROUND_LOCATION, ...), so a package only lists one
// here when it wants EVERY consumer to request it unconditionally - see each package's own
// native-link.json and README for which permissions it deliberately leaves for the app to add by
// hand instead (matching whatever upstream's own config-plugin defaults to `false`).
function patchAndroidManifestPermissions(appRoot, entries) {
  const wanted = new Set();
  for (const entry of entries) {
    const permissions = entry.manifest.android && entry.manifest.android.manifestPermissions;
    if (!permissions) continue;
    for (const permission of permissions) wanted.add(permission);
  }
  if (wanted.size === 0) return;

  const manifestPath = path.join(appRoot, 'android', 'app', 'src', 'main', 'AndroidManifest.xml');
  if (!fs.existsSync(manifestPath)) {
    dlog('AndroidManifest.xml not found, skipping permissions');
    return;
  }

  const content = fs.readFileSync(manifestPath, 'utf8');
  const existing = readManifestPermissions(content);
  const missing = [...wanted].filter((permission) => !existing.has(permission)).sort();
  if (missing.length === 0) return;

  const tag = findTag(content, 'manifest');
  if (!tag) {
    warn(`${manifestPath} has no <manifest> element, skipping permissions`);
    return;
  }

  const lines = missing.map((permission) => `  <uses-permission android:name="${permission}" />`).join('\n');
  const next = `${content.slice(0, tag.end + 1)}\n${lines}${content.slice(tag.end + 1)}`;

  applyIfChanged(manifestPath, content, next);
}

function readManifestServiceNames(content) {
  return new Set([...content.matchAll(/<service\s[^>]*android:name="([^"]+)"/g)].map((match) => match[1]));
}

function buildServiceXml(service, indent) {
  const attrs = [
    `android:name="${escapeXmlAttribute(service.name)}"`,
    `android:exported="${service.exported === true ? 'true' : 'false'}"`,
  ];
  if (service.foregroundServiceType) {
    attrs.push(`android:foregroundServiceType="${escapeXmlAttribute(service.foregroundServiceType)}"`);
  }
  const openTag = `${indent}<service ${attrs.join(' ')}`;
  if (!service.intentFilterActions || service.intentFilterActions.length === 0) {
    return `${openTag} />`;
  }
  const actions = service.intentFilterActions
    .map((action) => `${indent}    <action android:name="${escapeXmlAttribute(action)}" />`)
    .join('\n');
  return `${openTag}>\n${indent}  <intent-filter>\n${actions}\n${indent}  </intent-filter>\n${indent}</service>`;
}

// Sibling of patchAndroidManifestPermissions for a whole `<service>` ELEMENT rather than one
// `<uses-permission>` string — needed because a foreground service's native class is often not
// declared in the package's own AndroidManifest.xml either (unlike location's LocationTaskService,
// which ships in expo-location's own manifest and merges automatically): upstream's config-plugin
// adds it dynamically at `expo prebuild` time (e.g. expo-audio's AudioControlsService /
// AudioRecordingService, see plugin/src/withAudio.ts), which this project's static manifest-merge
// approach has no equivalent of until a package lists it here. Additive by `android:name`
// presence, same idempotency policy as every other patcher in this file.
function patchAndroidManifestServices(appRoot, entries) {
  const wanted = new Map();
  for (const entry of entries) {
    const services = entry.manifest.android && entry.manifest.android.manifestServices;
    if (!services) continue;
    for (const service of services) {
      if (!wanted.has(service.name)) wanted.set(service.name, service);
    }
  }
  if (wanted.size === 0) return;

  const manifestPath = path.join(appRoot, 'android', 'app', 'src', 'main', 'AndroidManifest.xml');
  if (!fs.existsSync(manifestPath)) {
    dlog('AndroidManifest.xml not found, skipping services');
    return;
  }

  const content = fs.readFileSync(manifestPath, 'utf8');
  const existing = readManifestServiceNames(content);
  const missing = [...wanted.values()]
    .filter((service) => !existing.has(service.name))
    .sort((a, b) => (a.name < b.name ? -1 : 1));
  if (missing.length === 0) return;

  const tag = findApplicationTag(content);
  if (!tag) {
    warn(`${manifestPath} has no <application> element, skipping services`);
    return;
  }
  if (content[tag.end - 1] === '/') {
    warn(`${manifestPath}'s <application> is self-closing, skipping services`);
    return;
  }

  const lastNewline = content.lastIndexOf('\n', tag.start);
  const tagIndent = /^[ \t]*/.exec(content.slice(lastNewline + 1, tag.start))[0];
  const indent = `${tagIndent}  `;
  const blocks = missing.map((service) => buildServiceXml(service, indent)).join('\n');
  const insertAt = tag.end + 1;
  const next = `${content.slice(0, insertAt)}\n${blocks}${content.slice(insertAt)}`;

  applyIfChanged(manifestPath, content, next);
}

function readPlistString(content, key) {
  const keyIndex = content.indexOf(`<key>${key}</key>`);
  if (keyIndex === -1) return null;
  const match = /<string>([\s\S]*?)<\/string>/.exec(content.slice(keyIndex));
  return match ? match[1] : null;
}

// No generated region here, unlike the Android files: Xcode rewrites Info.plist through its own
// serializer whenever target settings change, and that serializer drops XML comments. A lost END
// marker would make the next run insert a second block, producing duplicate keys and an invalid
// plist. So iOS stays additive, with `<key>NAME</key>` presence as the idempotency check.
//
// That means an existing key's VALUE is never overwritten. Intended: a description is
// user-facing App Store copy, so a hand-edit outranks a package default. Drift would then go
// unnoticed, hence the warning.
function patchInfoPlist(appRoot, entries) {
  const wanted = new Map();
  for (const entry of entries) {
    const keys = entry.manifest.ios && entry.manifest.ios.infoPlistKeys;
    if (!keys) continue;
    for (const [key, description] of Object.entries(keys)) {
      if (!wanted.has(key)) wanted.set(key, description);
    }
  }
  if (wanted.size === 0) return;

  const plistPath = findInfoPlistFile(appRoot);
  if (!plistPath) {
    dlog('Info.plist not found, skipping iOS permission strings');
    return;
  }

  const content = fs.readFileSync(plistPath, 'utf8');
  let next = content;

  for (const [key, description] of [...wanted].sort((a, b) => (a[0] < b[0] ? -1 : 1))) {
    const escaped = escapeXml(description);
    const existing = readPlistString(next, key);

    if (existing !== null) {
      if (existing !== escaped) {
        warn(
          `${key} in ${plistPath} reads "${existing}" but the package manifest says ` +
            `"${description}". Keeping the file as-is; edit it by hand if you want the manifest's.`,
        );
      }
      continue;
    }

    const plistCloseIndex = next.lastIndexOf('</plist>');
    const dictCloseIndex = next.lastIndexOf('</dict>', plistCloseIndex === -1 ? undefined : plistCloseIndex);
    if (dictCloseIndex === -1) {
      warn(`${plistPath} has no closing </dict>, skipping ${key}`);
      continue;
    }

    const block = `\t<key>${key}</key>\n\t<string>${escaped}</string>\n`;
    next = next.slice(0, dictCloseIndex) + block + next.slice(dictCloseIndex);
  }

  applyIfChanged(plistPath, content, next);
}

// Finds the `<key>NAME</key>` + `<array>…</array>` pair for an array-valued Info.plist key.
// Returns each item's raw (unescaped) string plus where the array closes, so a caller can append
// missing items without disturbing what's already there.
function readPlistArray(content, key) {
  const keyTag = `<key>${key}</key>`;
  const keyIndex = content.indexOf(keyTag);
  if (keyIndex === -1) return null;
  const arrayOpenIndex = content.indexOf('<array>', keyIndex + keyTag.length);
  const arrayCloseIndex = arrayOpenIndex === -1 ? -1 : content.indexOf('</array>', arrayOpenIndex);
  if (arrayOpenIndex === -1 || arrayCloseIndex === -1) return null;
  const inner = content.slice(arrayOpenIndex + '<array>'.length, arrayCloseIndex);
  const items = [...inner.matchAll(/<string>([\s\S]*?)<\/string>/g)].map((match) => match[1]);
  return { arrayCloseIndex, items };
}

// Sibling of patchInfoPlist for the one shape it cannot express: an ARRAY-valued key
// (UIBackgroundModes, BGTaskSchedulerPermittedIdentifiers, …) — a plain <string> would produce
// an invalid plist. Multiple packages can want the SAME key (background-fetch and background-task
// both add to UIBackgroundModes), so every package's items merge into one array instead of the
// last writer winning. Same additive policy as patchInfoPlist: an item already present, however it
// got there, is never removed or reordered.
function patchInfoPlistArrays(appRoot, entries) {
  const wanted = new Map();
  for (const entry of entries) {
    const arrayKeys = entry.manifest.ios && entry.manifest.ios.infoPlistArrayKeys;
    if (!arrayKeys) continue;
    for (const [key, items] of Object.entries(arrayKeys)) {
      if (!wanted.has(key)) wanted.set(key, new Set());
      for (const item of items) wanted.get(key).add(item);
    }
  }
  if (wanted.size === 0) return;

  const plistPath = findInfoPlistFile(appRoot);
  if (!plistPath) {
    dlog('Info.plist not found, skipping iOS array keys');
    return;
  }

  const content = fs.readFileSync(plistPath, 'utf8');
  let next = content;

  for (const [key, itemsSet] of [...wanted].sort((a, b) => (a[0] < b[0] ? -1 : 1))) {
    const wantedItems = [...itemsSet];
    const existing = readPlistArray(next, key);

    if (existing === null) {
      const plistCloseIndex = next.lastIndexOf('</plist>');
      const dictCloseIndex = next.lastIndexOf('</dict>', plistCloseIndex === -1 ? undefined : plistCloseIndex);
      if (dictCloseIndex === -1) {
        warn(`${plistPath} has no closing </dict>, skipping ${key}`);
        continue;
      }
      const itemLines = wantedItems.map((item) => `\t\t<string>${escapeXml(item)}</string>`).join('\n');
      const block = `\t<key>${key}</key>\n\t<array>\n${itemLines}\n\t</array>\n`;
      next = next.slice(0, dictCloseIndex) + block + next.slice(dictCloseIndex);
      continue;
    }

    const missing = wantedItems.filter((item) => !existing.items.includes(item));
    if (missing.length === 0) continue;

    const missingLines = missing.map((item) => `\t\t<string>${escapeXml(item)}</string>\n`).join('');
    next = next.slice(0, existing.arrayCloseIndex) + missingLines + next.slice(existing.arrayCloseIndex);
  }

  applyIfChanged(plistPath, content, next);
}

// Safe to run any number of times, and after an uninstall.
function linkApp(explicitAppRoot) {
  const appRoot = explicitAppRoot || findAppRoot();
  if (!appRoot) {
    warn('no React Native app here (no android/app/build.gradle, no ios/**/Info.plist), skipping');
    return;
  }

  const entries = collectManifests(appRoot);
  patchBuildGradle(appRoot, entries);
  patchMainApplication(appRoot, entries);
  patchAndroidManifest(appRoot, entries);
  patchAndroidManifestPermissions(appRoot, entries);
  patchAndroidManifestServices(appRoot, entries);
  patchInfoPlist(appRoot, entries);
  patchInfoPlistArrays(appRoot, entries);
}

module.exports = {
  linkApp,
  collectManifests,
  findAppRoot,
  findInfoPlistFile,
  findMainApplicationFile,
  patchBuildGradle,
  patchMainApplication,
  patchAndroidManifest,
  patchAndroidManifestPermissions,
  patchAndroidManifestServices,
  patchInfoPlist,
  patchInfoPlistArrays,
};
