import { Platform, UnavailabilityError } from 'expo-modules-core';
import { expoAppIntegrity } from './native-module';

const NATIVE_MODULE_NAME = 'expo-app-integrity';

/** @platform ios, true off ios since App Attest support has no Android/web equivalent */
export const isSupported: boolean =
  Platform.OS === 'ios' ? (expoAppIntegrity.isSupported ?? false) : true;

/** Creates a new App Attest key, stored in the Secure Enclave. @platform ios */
export async function generateKeyAsync(): Promise<string> {
  if (Platform.OS !== 'ios' || !expoAppIntegrity.generateKeyAsync) {
    throw new UnavailabilityError(NATIVE_MODULE_NAME, 'generateKeyAsync');
  }
  return expoAppIntegrity.generateKeyAsync();
}

/** Asks Apple to attest to the validity of a key generated by `generateKeyAsync`. @platform ios */
export async function attestKeyAsync(
  keyId: string,
  challenge: string,
): Promise<string> {
  if (Platform.OS !== 'ios' || !expoAppIntegrity.attestKeyAsync) {
    throw new UnavailabilityError(NATIVE_MODULE_NAME, 'attestKeyAsync');
  }
  return expoAppIntegrity.attestKeyAsync(keyId, challenge);
}

/** @platform ios */
export async function generateAssertionAsync(
  keyId: string,
  challenge: string,
): Promise<string> {
  if (Platform.OS !== 'ios' || !expoAppIntegrity.generateAssertionAsync) {
    throw new UnavailabilityError(NATIVE_MODULE_NAME, 'generateAssertionAsync');
  }
  return expoAppIntegrity.generateAssertionAsync(keyId, challenge);
}

/** @platform android */
export async function prepareIntegrityTokenProviderAsync(
  cloudProjectNumber: string,
): Promise<void> {
  if (
    Platform.OS !== 'android' ||
    !expoAppIntegrity.prepareIntegrityTokenProviderAsync
  ) {
    throw new UnavailabilityError(
      NATIVE_MODULE_NAME,
      'prepareIntegrityTokenProviderAsync',
    );
  }
  return expoAppIntegrity.prepareIntegrityTokenProviderAsync(
    cloudProjectNumber,
  );
}

/** @platform android */
export async function requestIntegrityCheckAsync(
  requestHash: string,
): Promise<string> {
  if (
    Platform.OS !== 'android' ||
    !expoAppIntegrity.requestIntegrityCheckAsync
  ) {
    throw new UnavailabilityError(
      NATIVE_MODULE_NAME,
      'requestIntegrityCheckAsync',
    );
  }
  return expoAppIntegrity.requestIntegrityCheckAsync(requestHash);
}

/** @platform android, `false` off android rather than throwing */
export async function isHardwareAttestationSupportedAsync(): Promise<boolean> {
  if (
    Platform.OS !== 'android' ||
    !expoAppIntegrity.isHardwareAttestationSupportedAsync
  ) {
    return false;
  }
  return expoAppIntegrity.isHardwareAttestationSupportedAsync();
}

/** Usable on GrapheneOS and other secure Android distributions. @platform android */
export async function generateHardwareAttestedKeyAsync(
  keyAlias: string,
  challenge: string,
): Promise<void> {
  if (
    Platform.OS !== 'android' ||
    !expoAppIntegrity.generateHardwareAttestedKeyAsync
  ) {
    throw new UnavailabilityError(
      NATIVE_MODULE_NAME,
      'generateHardwareAttestedKeyAsync',
    );
  }
  return expoAppIntegrity.generateHardwareAttestedKeyAsync(keyAlias, challenge);
}

/** Base64-encoded X.509 certificates, verify server-side. @platform android */
export async function getAttestationCertificateChainAsync(
  keyAlias: string,
): Promise<string[]> {
  if (
    Platform.OS !== 'android' ||
    !expoAppIntegrity.getAttestationCertificateChainAsync
  ) {
    throw new UnavailabilityError(
      NATIVE_MODULE_NAME,
      'getAttestationCertificateChainAsync',
    );
  }
  return expoAppIntegrity.getAttestationCertificateChainAsync(keyAlias);
}
