// Route-name constants shared between App.ts's <ng-template symbioteScreen name="..."> registrations
// and every screen's navigation.push(...)/navigation.jumpTo(...) calls — a single source of truth so
// a typo can't silently create a dead route on one side only. Byte-identical to the React canary's
// routes.ts (../react/routes.ts) — the route surface is framework-agnostic, only the wiring differs.

export const ROUTE_NAME = {
  Menu: 'Menu',
  Sensors: 'Sensors',
  LocalAuth: 'LocalAuth',
  Haptics: 'Haptics',
  Clipboard: 'Clipboard',
  Battery: 'Battery',
  Brightness: 'Brightness',
  Cellular: 'Cellular',
  Network: 'Network',
  Device: 'Device',
  Application: 'Application',
  Crypto: 'Crypto',
  StandardWebCrypto: 'StandardWebCrypto',
  SystemUi: 'SystemUi',
  StoreReview: 'StoreReview',
  KeepAwake: 'KeepAwake',
  ScreenOrientation: 'ScreenOrientation',
  Localization: 'Localization',
  TrackingTransparency: 'TrackingTransparency',
  SecureStore: 'SecureStore',
  Sharing: 'Sharing',
  WebBrowser: 'WebBrowser',
  Sms: 'Sms',
  Location: 'Location',
  MediaLibrary: 'MediaLibrary',
  FileSystem: 'FileSystem',
  Audio: 'Audio',
  Notifications: 'Notifications',
  BackgroundTasks: 'BackgroundTasks',
  Sqlite: 'Sqlite',
  MailComposer: 'MailComposer',
  Print: 'Print',
  Speech: 'Speech',
  VideoThumbnails: 'VideoThumbnails',
  DocumentPicker: 'DocumentPicker',
  ImagePicker: 'ImagePicker',
  ImageManipulator: 'ImageManipulator',
  Blob: 'Blob',
  ScreenCapture: 'ScreenCapture',
  Contacts: 'Contacts',
  Calendar: 'Calendar',
  AgeRange: 'AgeRange',
  AppIntegrity: 'AppIntegrity',
  IntentLauncher: 'IntentLauncher',
  NavigationBar: 'NavigationBar',
  Font: 'Font',
  Asset: 'Asset',
  AppMetrics: 'AppMetrics',
  AuthSession: 'AuthSession',
} as const;

export type IRouteName = (typeof ROUTE_NAME)[keyof typeof ROUTE_NAME];
