package com.canaryexpo

import android.app.Application
import com.facebook.react.PackageList
import com.facebook.react.ReactApplication
import com.facebook.react.ReactHost
import com.facebook.react.ReactNativeApplicationEntryPoint.loadReactNative
import com.facebook.react.defaults.DefaultReactHost.getDefaultReactHost
import expo.modules.adapters.react.ModuleRegistryAdapter
import expo.modules.adapters.react.ReactAdapterPackage
import expo.modules.adapters.react.ReactModuleRegistryProvider
import expo.modules.kotlin.ModulesProvider
import expo.modules.kotlin.modules.Module
// SYMBIOTE-EXPO-LINK:BEGIN IMPORTS (generated by symbiote-expo-link - do not edit, regenerated on every install)
import expo.modules.application.ApplicationModule
import expo.modules.audio.AudioModule
import expo.modules.backgroundfetch.BackgroundFetchModule
import expo.modules.backgroundtask.BackgroundTaskModule
import expo.modules.battery.BatteryModule
import expo.modules.brightness.BrightnessModule
import expo.modules.cellular.CellularModule
import expo.modules.clipboard.ClipboardModule
import expo.modules.crypto.CryptoModule
import expo.modules.device.DeviceModule
import expo.modules.filesystem.FileSystemModule
import expo.modules.filesystem.legacy.FileSystemLegacyModule
import expo.modules.haptics.HapticsModule
import expo.modules.keepawake.KeepAwakeModule
import expo.modules.localauthentication.LocalAuthenticationModule
import expo.modules.localization.LocalizationModule
import expo.modules.location.LocationModule
import expo.modules.medialibrary.MediaLibraryModule
import expo.modules.medialibrary.next.MediaLibraryNextModule
import expo.modules.network.NetworkModule
import expo.modules.notifications.badge.BadgeModule
import expo.modules.notifications.notifications.background.ExpoBackgroundNotificationTasksModule
import expo.modules.notifications.notifications.categories.ExpoNotificationCategoriesModule
import expo.modules.notifications.notifications.channels.NotificationChannelGroupManagerModule
import expo.modules.notifications.notifications.channels.NotificationChannelManagerModule
import expo.modules.notifications.notifications.emitting.NotificationsEmitter
import expo.modules.notifications.notifications.handling.NotificationsHandler
import expo.modules.notifications.notifications.presentation.ExpoNotificationPresentationModule
import expo.modules.notifications.notifications.scheduling.NotificationScheduler
import expo.modules.notifications.permissions.NotificationPermissionsModule
import expo.modules.notifications.serverregistration.ServerRegistrationModule
import expo.modules.notifications.tokens.PushTokenModule
import expo.modules.notifications.topics.TopicSubscriptionModule
import expo.modules.screenorientation.ScreenOrientationModule
import expo.modules.securestore.SecureStoreModule
import expo.modules.sensors.modules.AccelerometerModule
import expo.modules.sensors.modules.BarometerModule
import expo.modules.sensors.modules.DeviceMotionModule
import expo.modules.sensors.modules.GyroscopeModule
import expo.modules.sensors.modules.LightSensorModule
import expo.modules.sensors.modules.MagnetometerModule
import expo.modules.sensors.modules.MagnetometerUncalibratedModule
import expo.modules.sensors.modules.PedometerModule
import expo.modules.sharing.SharingModule
import expo.modules.sms.SMSModule
import expo.modules.sqlite.SQLiteModule
import expo.modules.storereview.StoreReviewModule
import expo.modules.systemui.SystemUIModule
import expo.modules.taskManager.TaskManagerModule
import expo.modules.trackingtransparency.TrackingTransparencyModule
import expo.modules.webbrowser.WebBrowserModule
// SYMBIOTE-EXPO-LINK:END IMPORTS

// No `expo` aggregator project here, so nothing auto-generates a module list. A missing entry
// fails at RUNTIME with "Cannot find native module '<Name>'", not at build time, and each key
// must match that module's own `definition() { Name("...") }` exactly (see the
// symbiote-expo-native-module skill). ModuleRegistryAdapter accepts only one ModulesProvider,
// so every package's modules share this map instead of each getting its own adapter.
private class ExpoModulesProvider : ModulesProvider {
  override fun getModulesMap(): Map<Class<out Module>, String?> = mapOf(
    // SYMBIOTE-EXPO-LINK:BEGIN MODULES-MAP (generated by symbiote-expo-link - do not edit, regenerated on every install)
    AccelerometerModule::class.java to "ExponentAccelerometer",
    ApplicationModule::class.java to "ExpoApplication",
    AudioModule::class.java to "ExpoAudio",
    BackgroundFetchModule::class.java to "ExpoBackgroundFetch",
    BackgroundTaskModule::class.java to "ExpoBackgroundTask",
    BadgeModule::class.java to "ExpoBadgeModule",
    BarometerModule::class.java to "ExpoBarometer",
    BatteryModule::class.java to "ExpoBattery",
    BrightnessModule::class.java to "ExpoBrightness",
    CellularModule::class.java to "ExpoCellular",
    ClipboardModule::class.java to "ExpoClipboard",
    CryptoModule::class.java to "ExpoCrypto",
    DeviceModule::class.java to "ExpoDevice",
    DeviceMotionModule::class.java to "ExponentDeviceMotion",
    ExpoBackgroundNotificationTasksModule::class.java to "ExpoBackgroundNotificationTasksModule",
    ExpoNotificationCategoriesModule::class.java to "ExpoNotificationCategoriesModule",
    ExpoNotificationPresentationModule::class.java to "ExpoNotificationPresenter",
    FileSystemLegacyModule::class.java to "ExponentFileSystem",
    FileSystemModule::class.java to "FileSystem",
    GyroscopeModule::class.java to "ExponentGyroscope",
    HapticsModule::class.java to "ExpoHaptics",
    KeepAwakeModule::class.java to "ExpoKeepAwake",
    LightSensorModule::class.java to "ExpoLightSensor",
    LocalAuthenticationModule::class.java to "ExpoLocalAuthentication",
    LocalizationModule::class.java to "ExpoLocalization",
    LocationModule::class.java to "ExpoLocation",
    MagnetometerModule::class.java to "ExponentMagnetometer",
    MagnetometerUncalibratedModule::class.java to "ExponentMagnetometerUncalibrated",
    MediaLibraryModule::class.java to "ExpoMediaLibrary",
    MediaLibraryNextModule::class.java to "ExpoMediaLibraryNext",
    NetworkModule::class.java to "ExpoNetwork",
    NotificationChannelGroupManagerModule::class.java to "ExpoNotificationChannelGroupManager",
    NotificationChannelManagerModule::class.java to "ExpoNotificationChannelManager",
    NotificationPermissionsModule::class.java to "ExpoNotificationPermissionsModule",
    NotificationScheduler::class.java to "ExpoNotificationScheduler",
    NotificationsEmitter::class.java to "ExpoNotificationsEmitter",
    NotificationsHandler::class.java to "ExpoNotificationsHandlerModule",
    PedometerModule::class.java to "ExponentPedometer",
    PushTokenModule::class.java to "ExpoPushTokenManager",
    SMSModule::class.java to "ExpoSMS",
    SQLiteModule::class.java to "ExpoSQLite",
    ScreenOrientationModule::class.java to "ExpoScreenOrientation",
    SecureStoreModule::class.java to "ExpoSecureStore",
    ServerRegistrationModule::class.java to "NotificationsServerRegistrationModule",
    SharingModule::class.java to "ExpoSharing",
    StoreReviewModule::class.java to "ExpoStoreReview",
    SystemUIModule::class.java to "ExpoSystemUI",
    TaskManagerModule::class.java to "ExpoTaskManager",
    TopicSubscriptionModule::class.java to "ExpoTopicSubscriptionModule",
    TrackingTransparencyModule::class.java to "ExpoTrackingTransparency",
    WebBrowserModule::class.java to "ExpoWebBrowser",
    // SYMBIOTE-EXPO-LINK:END MODULES-MAP
  )
}

class MainApplication : Application(), ReactApplication {

  override val reactHost: ReactHost by lazy {
    getDefaultReactHost(
      context = applicationContext,
      packageList =
        PackageList(this).packages.apply {
          // expo-modules-core has no react-native.config.js of its own, so RN's autolinking
          // never finds it — ModuleRegistryAdapter is the standard expo-modules-core/React
          // bridge, wired manually like any package autolinking can't reach.
          add(
            ModuleRegistryAdapter(
              ReactModuleRegistryProvider(listOf(ReactAdapterPackage())),
              ExpoModulesProvider(),
            ),
          )
        },
    )
  }

  override fun onCreate() {
    super.onCreate()
    loadReactNative(this)
  }
}
